export const BackendOptions = [
  { value: "Backend", label: "Backend", isDisabled: true },

  //   Pr Languages with Frameworks
  { value: "python", label: "Python" },
  { value: "django", label: "Django" },
  { value: "fastapi", label: "FastAPI" },
  { value: "flask", label: "Flask" },

  { value: "javascript", label: "JavaScript" },
  { value: "typescript", label: "TypeScript" },
  { value: "nodejs", label: "Node.js" },
  { value: "expressjs", label: "Express.js" },
  { value: "koajs", label: "Koa.js" },
  { value: "nestjs", label: "Nest.js" },
  { value: "sailsjs", label: "Sails.js" },
  { value: "svelte", label: "Svelte" },

  { value: "php", label: "PHP" },
  { value: "laravel", label: "Laravel" },
  { value: "symfony", label: "Symfony" },
  { value: "codeigniter", label: "CodeIgniter" },
  { value: "cakephp", label: "CakePHP" },

  { value: "csharp", label: "C#" },
  { value: "aspdotnet", label: "ASP.NET" },
  { value: "dotnet", label: ".NET" },
  { value: "unity", label: "Unity" },

  { value: "java", label: "Java" },
  { value: "springboot", label: "Spring Boot" },
  { value: "hibernate", label: "Hibernate" },
  { value: "struts", label: "Struts" },

  { value: "apache", label: "Apache" },
  { value: "apachekafka", label: "Apache Kafka" },
  { value: "apachespark", label: "Apache Spark" },
  { value: "apachehadoop", label: "Apache Hadoop" },

  { value: "ruby", label: "Ruby" },
  { value: "rubyonrails", label: "Ruby on Rails" },

  { value: "go", label: "Go" },
  { value: "sinatra", label: "Sinatra" },
  { value: "Cpp", label: "C++" },
  { value: "meteor", label: "Meteor" },
  { value: "playframework", label: "Play Framework" },
  { value: "rust", label: "Rust" },
  { value: "kotlin", label: "Kotlin" },
  { value: "perl", label: "Perl" },
  { value: "matlab", label: "Matlab" },
  { value: "lua", label: "Lua" },
  { value: "ada", label: "Ada" },
  { value: "fortran", label: "Fortran" },
  { value: "scala", label: "Scala" },

  //   SQL & NoSQL Databases & Clouds
  { value: "postgresql", label: "PostgreSQL" },
  { value: "firebase", label: "Firebase" },
  { value: "mysql", label: "MySQL" },
  { value: "mongodb", label: "MongoDB" },
  { value: "dynamodb", label: "DynamoDB" },
  { value: "redis", label: "Redis" },
  { value: "sqllite", label: "SQLlite" },
  { value: "cdn", label: "CDN" },
  { value: "storage", label: "Storage" },
  { value: "streamingstorage", label: "Streaming Storage" },
  { value: "cache", label: "Cache" },
  { value: "database", label: "Database" },
  { value: "cloud", label: "Cloud" },
  { value: "server", label: "Server" },
  { value: "sql", label: "SQL" },
  { value: "awscloud", label: "Amazon Web Services (AWS)" },
  { value: "gcpcloud", label: "Google Cloud Platform (GCP)" },
  { value: "macloud", label: "Microsoft Azure (MA)" },
  { value: "elasticsearch", label: "ElasticSearch" },

  //   Coding Platforms
  { value: "vscode", label: "Visual Studio Code" },
  { value: "atom", label: "Atom" },
  { value: "sublimetext", label: "Sublime Text" },
  { value: "eclipse", label: "Eclipse" },
  { value: "netbeans", label: "NetBeans" },
  { value: "visualstudio", label: "Visual Studio" },

  //   DevOps
  { value: "devops", label: "DevOps" },
  { value: "cicd", label: "CI/CD" },
  { value: "git", label: "Git" },
  { value: "github", label: "GitHub" },
  { value: "gitlab", label: "GitLab" },
  { value: "bitbucket", label: "BitBucket" },
  { value: "docker", label: "Docker" },
  { value: "kubernetes", label: "Kubernetes" },
  { value: "jenkins", label: "Jenkins" },
  { value: "circleci", label: "CircleCI" },
  { value: "travisci", label: "Travis CI" },
  { value: "virtualbox", label: "VirtualBox" },

  //   Software Architecture
  { value: "computerarchitecture", label: "Computer Architecture" },
  { value: "architecture", label: "Architecture" },
  { value: "microservices", label: "Microservices" },
  { value: "systemdesign", label: "System Design" },
  { value: "performance", label: "Performance" },
  { value: "optimization", label: "Optimization" },
  { value: "webbackend", label: "Web Backend" },
  { value: "fullstack", label: "Full-Stack" },
  { value: "mobilebackend", label: "Mobile Backend" },
  { value: "test", label: "Test" }, // { value: "Postman", label: "Postman" },

  // Backend Topics
  { value: "grpc", label: "GRPC" },
  { value: "realtime", label: "Real-Time" },
  { value: "smtp", label: "SMTP" },
  { value: "api", label: "API" },
  { value: "metrics", label: "Metrics" },
  { value: "documentation", label: "Documentation" },
  { value: "authentication", label: "Authentication" },
  { value: "security", label: "Security" },
  { value: "swagger", label: "Swagger" },
  { value: "library", label: "Library" },
  { value: "network", label: "Network" },
  { value: "production", label: "Production" },

  // Mixed
  { value: "development", label: "Development" },
  { value: "drone", label: "Drone" },
  { value: "json", label: "JSON" },
  { value: "decoder", label: "Decoder" },
  { value: "readme", label: "README" },
  { value: "awesome", label: "Awesome" },
  { value: "startup", label: "Startup" },
  { value: "code", label: "Code" },
  { value: "iot", label: "IoT" },
  { value: "macos", label: "MacOS" },
  { value: "interview", label: "Interview" },
  { value: "search", label: "Search" },
  { value: "projects", label: "Projects" },
  { value: "cheatsheet", label: "CheatSheet" },
  { value: "3rdparty", label: "3rdParty" },
];
