export const FrontendOptions = [
  { value: "Frontend", label: "Frontend", isDisabled: true },
  // Frontend Layouts
  { value: "contentlayout", label: "Content (lyt)" },
  { value: "footerlayout", label: "Footer (lyt)" },
  { value: "formslayout", label: "Forms (lyt)" },
  { value: "headerlayout", label: "Header (lyt)" },
  { value: "herolayout", label: "Hero (lyt)" },
  { value: "navbarlayout", label: "Navbar (lyt)" },

  // Frontend Components
  { value: "Components", label: "Components" },
  { value: "buttoncomp", label: "Button (comp)" },
  { value: "carouselcomp", label: "Carousel (comp)" },
  { value: "checkboxcomp", label: "Checkbox (comp)" },
  { value: "countdowncomp", label: "Countdown (comp)" },
  { value: "datepickercomp", label: "Datepicker (comp)" },
  { value: "fileinputcomp", label: "File Input (comp)" },
  { value: "inputfieldcomp", label: "Input Field (comp)" },
  { value: "loadercomp", label: "Loader (comp)" },
  { value: "radiocomp", label: "Radio (comp)" },
  { value: "rangeslidercomp", label: "Range Slider (comp)" },
  { value: "selectcomp", label: "Select (comp)" },
  { value: "spinnercomp", label: "Spinner (comp)" },
  { value: "textareacomp", label: "Textarea (comp)" },
  { value: "togglecomp", label: "Toggle (comp)" },
  { value: "tooltipscomp", label: "Tooltips (comp)" },

  // Frontend Sections
  { value: "Sections", label: "Sections" },
  // AAAA
  { value: "aboutsection", label: "About (sec)" },
  { value: "accordionsection", label: "Accordion (sec)" },
  { value: "alertsection", label: "Alert (sec)" },
  { value: "applicationshellsection", label: "Application Shell (sec)" },
  { value: "avatarsection", label: "Avatar (sec)" },
  // BBBB
  { value: "badgessection", label: "Badges (sec)" },
  { value: "bannersection", label: "Banner (sec)" },
  { value: "blockquotesection", label: "Blockquote (sec)" },
  { value: "blogsection", label: "Blog (sec)" },
  { value: "bottomnavigationsection", label: "Bottom Navigation (sec)" },
  { value: "breadcrumbssection", label: "Breadcrumbs (sec)" },
  { value: "buttongroupsection", label: "Button Group (sec)" },
  // CCCC
  { value: "cardssection", label: "Cards (sec)" },
  { value: "cartsection", label: "Cart (sec)" },
  { value: "checkoutsection", label: "Checkout (sec)" },
  { value: "commentssection", label: "Comments (sec)" },
  { value: "contactssection", label: "Contacts (sec)" },
  { value: "cookiesection", label: "Cookie (sec)" },
  { value: "ctasection", label: "CTA (sec)" },
  // DDDD
  { value: "devicemockupsection", label: "Device Mockup (sec)" },
  { value: "dividersection", label: "Divider (sec)" },
  { value: "draweroffcanvassection", label: "Drawer (offcanvas) (sec)" },
  { value: "dropdownfiltersection", label: "Dropdown Filter (sec)" },
  { value: "dropdownsection", label: "Dropdown (sec)" },
  // EEEE
  { value: "errorBarsection", label: "ErrorBar (sec)" },
  // FFFF
  { value: "fAQsection", label: "FAQ (sec)" },
  { value: "featuressection", label: "Features (sec)" },
  { value: "floatinglabelsection", label: "Floating Label (sec)" },
  // GGGG
  { value: "gallerysection", label: "Gallery (sec)" },
  // HHHH
  {
    value: "horizontallinesection",
    label: "horizontal Line (HR) (sec)",
  },
  // IIII
  { value: "imagesection", label: "Image (sec)" },
  { value: "indicatorssection", label: "Indicators (sec)" },
  // JJJJ
  { value: "jumbotronsection", label: "Jumbotron (sec)" },
  // KKKK
  { value: "kbdkeyboardsection", label: "KBD (Keyboard) (sec)" },
  // LLLL
  { value: "linksection", label: "Link (sec)" },
  { value: "listgroupsection", label: "List Group (sec)" },
  { value: "listsection", label: "List (sec)" },
  { value: "loginformsection", label: "Login Form (sec)" },
  { value: "logoutformsection", label: "Logout Form (sec)" },
  // MMMM
  { value: "megamenusection", label: "Mega Menu (sec)" },
  { value: "menusection", label: "Menu (sec)" },
  { value: "modalsection", label: "Modal (sec)" },
  // NNNN
  { value: "newslettersection", label: "Newsletter (sec)" },
  // OOOO
  // PPPP
  { value: "paginationsection", label: "Pagination (sec)" },
  { value: "paragraphsection", label: "Paragraph (sec)" },
  { value: "partnerssection", label: "Partners (sec)" },
  { value: "popoversection", label: "Popover (sec)" },
  { value: "popupsection", label: "Popup (sec)" },
  { value: "pricingsection", label: "Pricing (sec)" },
  { value: "progressbarsection", label: "Progress bar (sec)" },
  // QQQQ
  // RRRR
  { value: "ratingsection", label: "Rating (sec)" },
  // SSSS
  { value: "searchinputsection", label: "Search Input (sec)" },
  { value: "sidebarsection", label: "Sidebar (sec)" },
  { value: "sidenavigationsection", label: "Side Navigation (sec)" },
  { value: "signupformsection", label: "Sign Up Form (sec)" },
  { value: "skeletonsection", label: "Skeleton (sec)" },
  { value: "speeddailsection", label: "Speed Dail (sec)" },
  { value: "stacksection", label: "Stack (sec)" },
  { value: "statisticssection", label: "Statistics (sec)" },
  { value: "stepperssection", label: "Steppers (sec)" },
  { value: "stepssection", label: "Steps (sec)" },
  { value: "stickybannersection", label: "Sticky Banner (sec)" },
  { value: "swapsection", label: "Swap (sec)" },
  // TTTT
  { value: "tableheadersection", label: "Table Header (sec)" },
  { value: "tablesection", label: "Table (sec)" },
  { value: "tabssection", label: "Tabs (sec)" },
  { value: "teamsection", label: "Team (sec)" },
  { value: "testimonialsection", label: "Testimonial (sec)" },
  { value: "textsection", label: "Text (sec)" },
  { value: "timelinesection", label: "Timeline (sec)" },
  { value: "toastsection", label: "Toast (sec)" },
  // VVVV
  { value: "videosection", label: "Video (sec)" },

  // Frontend Development
  { value: "Accessibility", label: "Accessibility" },
  { value: "Architecture", label: "Architecture" },
  { value: "Chrome DevTool", label: "Chrome DevTool" },
  { value: "Code", label: "Code" },
  { value: "Database", label: "Database" },
  { value: "Development", label: "Development" },
  { value: "Documentation", label: "Documentation" },
  { value: "JSON", label: "JSON" },
  { value: "Meta Tags", label: "Meta Tags" },
  { value: "Optimization", label: "Optimization" },
  { value: "Performance", label: "Performance" },
  { value: "Responsive", label: "Responsive" },
  { value: "Privacy", label: "Privacy" },
  { value: "PWA", label: "PWA" },
  { value: "QR Code", label: "QR Code" },
  { value: "SEO", label: "SEO" },
  { value: "Shortcut", label: "Shortcut" },
  { value: "SSR", label: "Server Sided Rendering (SSR)" },
  { value: "Structured Data", label: "Structured Data" },
  { value: "Test", label: "Test" },
  { value: "Web", label: "Web" },

  // Frontend Library
  { value: "Library", label: "Library" },
  { value: "WebRTC", label: "WebRTC" }, // Think of smth for this kind of libraries
  { value: "Angular.js", label: "Angular.js" },
  { value: "Next.js", label: "Next.js" },
  { value: "Nuxt.js", label: "Nuxt.js" },
  { value: "React.js", label: "React.js" },
  { value: "Vue.js", label: "Vue.js" },
  // Frontend UI/UX Design
  { value: "UIDesign", label: "UIDesign" },
  { value: "Icon", label: "Icon" },
  { value: "Video", label: "Video" },
  { value: "Picture", label: "Picture" },
  { value: "Color", label: "Color" },
  { value: "Gradient Color", label: "Gradient Color" },
  { value: "illustration", label: "illustration" },
  { value: "Inspiration", label: "Inspiration" },
  { value: "Typography", label: "Typography" },
  { value: "Font", label: "Font" },
  { value: "Music", label: "Music" },
  { value: "Animation", label: "Animation" },
  { value: "Pattern", label: "Pattern" },
  { value: "Blob", label: "Blob" },
  { value: "Wave", label: "Wave" },
  { value: "Emoji", label: "Emoji" },

  { value: "Interface", label: "Interface" },
  { value: "IOS", label: "IOS" },
  { value: "Android", label: "Android" },
  { value: "Google", label: "Google" },
  { value: "Desktop", label: "Desktop" },
  { value: "Screen", label: "Screen" },
  { value: "Awesome", label: "Awesome" },
  { value: "3D Image", label: "3D Image" },
  { value: "Social Media", label: "Social Media" },
  { value: "GIF", label: "GIF" },
  { value: "Template", label: "Template" },
  { value: "Wireframe", label: "Wireframe" },
  { value: "Logo", label: "Logo" },
  { value: "Prototype", label: "Prototype" },

  // Frontend Tools
  { value: "DesignTools", label: "DesignTools" },
  { value: "Adobe Illustrator", label: "Adobe Illustrator" }, // prototyping
  { value: "Adobe Photoshop", label: "Adobe Photoshop" },
  { value: "Adobe XD", label: "Adobe XD" },
  { value: "Sketch", label: "Sketch" },
  { value: "Figma", label: "Figma" },
  { value: "CSS", label: "CSS" }, // ui design code
  { value: "Bootstrap", label: "Bootstrap" },
  { value: "Sass", label: "Sass" },
  { value: "PostCSS", label: "PostCSS" },
  { value: "TailwindCSS", label: "TailwindCSS" },
  { value: "Less", label: "Less" },
  { value: "Styled Components", label: "Styled Components" },
  { value: "Generators", label: "Generators" },
  { value: "HTML", label: "HTML" },
  { value: "AI", label: "AI" },
  { value: "Extension", label: "Extension" },
  { value: "API", label: "API" },
  { value: "Browser", label: "Browser" },
  { value: "NoCode", label: "NoCode" },
  { value: "VS Code Tool", label: "VS Code Tool" },
  { value: "InVision Studio", label: "InVision Studio" },

  // Frontend Mixed
  { value: "Marketing", label: "Marketing" },
  { value: "Business", label: "Business" },
  { value: "Brand", label: "Brand" },
  { value: "Collection", label: "Collection" },
  { value: "Ant Design", label: "Ant Design" },
  { value: "Neumorphism", label: "Neumorphism" },
  { value: "Claymorphism", label: "Claymorphism" },
  { value: "Glassmorphism", label: "Glassmorphism" },
  { value: "GitHub", label: "GitHub" },

  //   Designer
  { value: "Designer", label: "Designer", isDisabled: true },
  { value: "User Reasercher", label: "User Reasercher" },
  { value: "Visual Designer", label: "Visual Designer" },
  { value: "Creative Director", label: "Creative Director" },
  { value: "Graphic Designer", label: "Graphic Designer" },
  { value: "Design Manager", label: "Design Manager" },
];
export const CategoryOptions = [
  { value: "frontend", label: "Frontend" },
  { value: "backend", label: "Backend" },
  { value: "mobile", label: "Mobile" },
  { value: "blogs", label: "Blogs" },
  { value: "podcasts", label: "Podcasts" },
  { value: "datascience", label: "AI / ML / DS" },
  { value: "algorithms", label: "Algorithms" },
  { value: "courses", label: "IT Courses" },
  { value: "cybersecurity", label: "Cyber Security" },
];
export const BlogOptions = [
  { value: "Blogs", label: "Blogs", isDisabled: true },
  { value: "frontend", label: "Frontend" },
  { value: "backend", label: "Backend" },
  { value: "mobile", label: "Mobile" },
  { value: "blogs", label: "Blogs" },
  { value: "podcasts", label: "Podcasts" },
  { value: "datascience", label: "AI / ML / DS" },
  { value: "algorithms", label: "Algorithms" },
  { value: "courses", label: "IT Courses" },
  { value: "cybersecurity", label: "Cyber Security" },
];
export const CourseOptions = [
  { value: "IT Courses", label: "IT Courses", isDisabled: true },
  { value: "frontend", label: "Frontend" },
  { value: "backend", label: "Backend" },
  { value: "mobile", label: "Mobile" },
  { value: "blogs", label: "Blogs" },
  { value: "podcasts", label: "Podcasts" },
  { value: "datascience", label: "AI / ML / DS" },
  { value: "algorithms", label: "Algorithms" },
  { value: "courses", label: "IT Courses" },
  { value: "cybersecurity", label: "Cyber Security" },
];
export const PodcastOptions = [
  { value: "Podcasts", label: "Podcasts", isDisabled: true },
  { value: "frontend", label: "Frontend" },
  { value: "backend", label: "Backend" },
  { value: "mobile", label: "Mobile" },
  { value: "blogs", label: "Blogs" },
  { value: "podcasts", label: "Podcasts" },
  { value: "datascience", label: "AI / ML / DS" },
  { value: "algorithms", label: "Algorithms" },
  { value: "courses", label: "IT Courses" },
  { value: "cybersecurity", label: "Cyber Security" },
];
export const AlgorithmsOptions = [
  { value: "Algorithms", label: "Algorithms", isDisabled: true },
  { value: "frontend", label: "Frontend" },
  { value: "backend", label: "Backend" },
  { value: "mobile", label: "Mobile" },
  { value: "blogs", label: "Blogs" },
  { value: "podcasts", label: "Podcasts" },
  { value: "datascience", label: "AI / ML / DS" },
  { value: "algorithms", label: "Algorithms" },
  { value: "courses", label: "IT Courses" },
  { value: "cybersecurity", label: "Cyber Security" },
];
export const MobileOptions = [
  { value: "Mobile", label: "Mobile", isDisabled: true },
  { value: "frontend", label: "Frontend" },
  { value: "backend", label: "Backend" },
  { value: "mobile", label: "Mobile" },
  { value: "blogs", label: "Blogs" },
  { value: "podcasts", label: "Podcasts" },
  { value: "datascience", label: "AI / ML / DS" },
  { value: "algorithms", label: "Algorithms" },
  { value: "courses", label: "IT Courses" },
  { value: "cybersecurity", label: "Cyber Security" },
];
export const AIOptions = [
  { value: "AI", label: "AI", isDisabled: true },
  { value: "frontend", label: "Frontend" },
  { value: "backend", label: "Backend" },
  { value: "mobile", label: "Mobile" },
  { value: "blogs", label: "Blogs" },
  { value: "podcasts", label: "Podcasts" },
  { value: "datascience", label: "AI / ML / DS" },
  { value: "algorithms", label: "Algorithms" },
  { value: "courses", label: "IT Courses" },
  { value: "cybersecurity", label: "Cyber Security" },
];
export const SecurityOptions = [
  { value: "Cyber Security", label: "Cyber Security", isDisabled: true },
  { value: "frontend", label: "Frontend" },
  { value: "backend", label: "Backend" },
  { value: "mobile", label: "Mobile" },
  { value: "blogs", label: "Blogs" },
  { value: "podcasts", label: "Podcasts" },
  { value: "datascience", label: "AI / ML / DS" },
  { value: "algorithms", label: "Algorithms" },
  { value: "courses", label: "IT Courses" },
  { value: "cybersecurity", label: "Cyber Security" },
];

export const BackendOptions = [
  { value: "Backend", label: "Backend", isDisabled: true },

  //   Pr Languages with Frameworks
  { value: "python", label: "Python" },
  { value: "django", label: "Django" },
  { value: "fastapi", label: "FastAPI" },
  { value: "flask", label: "Flask" },

  { value: "javascript", label: "JavaScript" },
  { value: "typescript", label: "TypeScript" },
  { value: "nodejs", label: "Node.js" },
  { value: "expressjs", label: "Express.js" },
  { value: "koajs", label: "Koa.js" },
  { value: "nestjs", label: "Nest.js" },
  { value: "sailsjs", label: "Sails.js" },
  { value: "svelte", label: "Svelte" },

  { value: "php", label: "PHP" },
  { value: "laravel", label: "Laravel" },
  { value: "symfony", label: "Symfony" },
  { value: "codeigniter", label: "CodeIgniter" },
  { value: "cakephp", label: "CakePHP" },

  { value: "csharp", label: "C#" },
  { value: "aspdotnet", label: "ASP.NET" },
  { value: "dotnet", label: ".NET" },
  { value: "unity", label: "Unity" },

  { value: "java", label: "Java" },
  { value: "springboot", label: "Spring Boot" },
  { value: "hibernate", label: "Hibernate" },
  { value: "struts", label: "Struts" },

  { value: "apache", label: "Apache" },
  { value: "apachekafka", label: "Apache Kafka" },
  { value: "apachespark", label: "Apache Spark" },
  { value: "apachehadoop", label: "Apache Hadoop" },

  { value: "ruby", label: "Ruby" },
  { value: "rubyonrails", label: "Ruby on Rails" },

  { value: "go", label: "Go" },
  { value: "sinatra", label: "Sinatra" },
  { value: "Cpp", label: "C++" },
  { value: "meteor", label: "Meteor" },
  { value: "playframework", label: "Play Framework" },
  { value: "rust", label: "Rust" },
  { value: "kotlin", label: "Kotlin" },
  { value: "perl", label: "Perl" },
  { value: "matlab", label: "Matlab" },
  { value: "lua", label: "Lua" },
  { value: "ada", label: "Ada" },
  { value: "fortran", label: "Fortran" },
  { value: "scala", label: "Scala" },

  //   SQL & NoSQL Databases & Clouds
  { value: "postgresql", label: "PostgreSQL" },
  { value: "firebase", label: "Firebase" },
  { value: "mysql", label: "MySQL" },
  { value: "mongodb", label: "MongoDB" },
  { value: "dynamodb", label: "DynamoDB" },
  { value: "redis", label: "Redis" },
  { value: "sqllite", label: "SQLlite" },
  { value: "cdn", label: "CDN" },
  { value: "storage", label: "Storage" },
  { value: "streamingstorage", label: "Streaming Storage" },
  { value: "cache", label: "Cache" },
  { value: "database", label: "Database" },
  { value: "cloud", label: "Cloud" },
  { value: "server", label: "Server" },
  { value: "sql", label: "SQL" },
  { value: "awscloud", label: "Amazon Web Services (AWS)" },
  { value: "gcpcloud", label: "Google Cloud Platform (GCP)" },
  { value: "macloud", label: "Microsoft Azure (MA)" },
  { value: "elasticsearch", label: "ElasticSearch" },

  //   Coding Platforms
  { value: "vscode", label: "Visual Studio Code" },
  { value: "atom", label: "Atom" },
  { value: "sublimetext", label: "Sublime Text" },
  { value: "eclipse", label: "Eclipse" },
  { value: "netbeans", label: "NetBeans" },
  { value: "visualstudio", label: "Visual Studio" },

  //   DevOps
  { value: "devops", label: "DevOps" },
  { value: "cicd", label: "CI/CD" },
  { value: "git", label: "Git" },
  { value: "github", label: "GitHub" },
  { value: "gitlab", label: "GitLab" },
  { value: "bitbucket", label: "BitBucket" },
  { value: "docker", label: "Docker" },
  { value: "kubernetes", label: "Kubernetes" },
  { value: "jenkins", label: "Jenkins" },
  { value: "circleci", label: "CircleCI" },
  { value: "travisci", label: "Travis CI" },
  { value: "virtualbox", label: "VirtualBox" },

  //   Software Architecture
  { value: "computerarchitecture", label: "Computer Architecture" },
  { value: "architecture", label: "Architecture" },
  { value: "microservices", label: "Microservices" },
  { value: "systemdesign", label: "System Design" },
  { value: "performance", label: "Performance" },
  { value: "optimization", label: "Optimization" },
  { value: "webbackend", label: "Web Backend" },
  { value: "fullstack", label: "Full-Stack" },
  { value: "mobilebackend", label: "Mobile Backend" },
  { value: "test", label: "Test" }, // { value: "Postman", label: "Postman" },

  // Backend Topics
  { value: "grpc", label: "GRPC" },
  { value: "realtime", label: "Real-Time" },
  { value: "smtp", label: "SMTP" },
  { value: "api", label: "API" },
  { value: "metrics", label: "Metrics" },
  { value: "documentation", label: "Documentation" },
  { value: "authentication", label: "Authentication" },
  { value: "security", label: "Security" },
  { value: "swagger", label: "Swagger" },
  { value: "library", label: "Library" },
  { value: "network", label: "Network" },
  { value: "production", label: "Production" },

  // Mixed
  { value: "development", label: "Development" },
  { value: "drone", label: "Drone" },
  { value: "json", label: "JSON" },
  { value: "decoder", label: "Decoder" },
  { value: "readme", label: "README" },
  { value: "awesome", label: "Awesome" },
  { value: "startup", label: "Startup" },
  { value: "code", label: "Code" },
  { value: "iot", label: "IoT" },
  { value: "macos", label: "MacOS" },
  { value: "interview", label: "Interview" },
  { value: "search", label: "Search" },
  { value: "projects", label: "Projects" },
  { value: "cheatsheet", label: "CheatSheet" },
  { value: "3rdparty", label: "3rdParty" },
];

export const PricingOptions = [
  { value: "free", label: "Free" },
  { value: "paid", label: "Paid" },
  { value: "freemium", label: "Freemium" },
  { value: "free+paid", label: "Free+Paid" },
];
