export const FrontendOptions = [
  { value: "Frontend", label: "Frontend", isDisabled: true },
  { value: "Error Page", label: "Error Page" },
  { value: "Comments Section", label: "Comments Section" },
  { value: "Cookie", label: "Cookie" },
  { value: "Banner", label: "Banner" },
  { value: "Testimonial", label: "Testimonial" },
  { value: "FAQ Section", label: "FAQ Section" },
  { value: "Popup", label: "Popup" },
  { value: "Blog Page", label: "Blog Page" },
  { value: "Pricing Section", label: "Pricing Section" },
  { value: "Dropdown Filter", label: "Dropdown Filter" },
  { value: "Application Shell", label: "Application Shell" },
  { value: "Team Section", label: "Team Section" },
  { value: "Header", label: "Header" },
  { value: "Content Section", label: "Content Section" },
  { value: "CTA Section", label: "CTA Section" },
  { value: "Feature Section", label: "Feature Section" },
  { value: "Side Navigation", label: "Side Navigation" },
  { value: "Table Header", label: "Table Header" },
  { value: "Hero Section", label: "Hero Section" },
  { value: "Device Mockup", label: "Device Mockup" },
  { value: "Jumbotron", label: "Jumbotron" },
  { value: "Gallery Section", label: "Gallery Section" },
  { value: "Sticky Banner", label: "Sticky Banner" },
  { value: "Bottom Navigation", label: "Bottom Navigation" },
  { value: "Indicators", label: "Indicators" },
  { value: "Steppers", label: "Steppers" },
  { value: "Horizontal Line (HR)", label: "Horizontal Line (HR)" },
  { value: "Text", label: "Text" },
  { value: "Link", label: "Link" },
  { value: "List", label: "List" },
  { value: "Image", label: "Image" },
  { value: "Blockquote", label: "Blockquote" },
  { value: "Paragraph", label: "Paragraph" },
  { value: "Heading Section", label: "Heading Section" },
  { value: "Video Section", label: "Video Section" },
  { value: "Video", label: "Video" },
  { value: "Popover", label: "Popover" },
  { value: "Drawer (offcanvas)", label: "Drawer (offcanvas)" },
  { value: "KBD (Keyboard)", label: "KBD (Keyboard)" },
  { value: "Skeleton", label: "Skeleton" },
  { value: "Mega Menu", label: "Mega Menu" },
  { value: "Floating Label", label: "Floating Label" },
  { value: "Range Slider", label: "Range Slider" },
  { value: "Toggle", label: "Toggle" },
  { value: "Radio", label: "Radio" },
  { value: "Checkbox", label: "Checkbox" },
  { value: "Textarea", label: "Textarea" },
  { value: "Select", label: "Select" },
  { value: "Search Input", label: "Search Input" },
  { value: "File Input", label: "File Input" },
  { value: "Input Field", label: "Input Field" },
  { value: "Datepicker", label: "Datepicker" },
  { value: "Tooltips", label: "Tooltips" },
  { value: "Toast", label: "Toast" },
  { value: "Spinner", label: "Spinner" },
  { value: "Table", label: "Table" },
  { value: "Progress bar", label: "Progress bar" },
  { value: "Timeline", label: "Timeline" },
  { value: "Rating", label: "Rating" },
  { value: "Speed Dail", label: "Speed Dail" },
  { value: "Pagination", label: "Pagination" },
  { value: "Sidebar", label: "Sidebar" },
  { value: "Footer", label: "Footer" },
  { value: "Navbar", label: "Navbar" },
  { value: "Tabs", label: "Tabs" },
  { value: "Modal", label: "Modal" },
  { value: "Typography", label: "Typography" },
  { value: "List Group", label: "List Group" },
  { value: "Forms", label: "Forms" },
  { value: "Dropdown", label: "Dropdown" },
  { value: "Carousel", label: "Carousel" },
  { value: "Cards", label: "Cards" },
  { value: "Figma", label: "Figma" },
  { value: "Alert", label: "Alert" },
  { value: "Accordion", label: "Accordion" },
  { value: "Avatar", label: "Avatar" },
  { value: "Badges", label: "Badges" },
  { value: "Components", label: "Components" },
  { value: "SVG", label: "SVG" },
  { value: "DesignTools", label: "DesignTools" },
  { value: "Breadcrumbs", label: "Breadcrumbs" },
  { value: "Template", label: "Template" },
  { value: "TailwindCSS", label: "TailwindCSS" },
  { value: "Picture", label: "Picture" },
  { value: "Buttons", label: "Buttons" },
  { value: "Generators", label: "Generators" },
  { value: "Color", label: "Color" },
  { value: "Button Group", label: "Button Group" },
  { value: "SEO", label: "SEO" },
  { value: "Redux", label: "Redux" },
  { value: "CSS", label: "CSS" },
  { value: "HTML", label: "HTML" },
  { value: "WebRTC", label: "WebRTC" },
  { value: "WebSocket", label: "WebSocket" },
  { value: "Chrome DevTool", label: "Chrome DevTool" },
  { value: "Countdown", label: "Countdown" },
  { value: "Divider", label: "Divider" },
  { value: "Loader", label: "Loader" },
  { value: "Menu", label: "Menu" },
  { value: "Stack", label: "Stack" },
  { value: "Steps", label: "Steps" },
  { value: "Swap", label: "Swap" },
  { value: "Login Form", label: "Login Form" },
  { value: "Logout Form", label: "Logout Form" },
  { value: "Authentication Form", label: "Authentication Form" },
  { value: "Sign Up Form", label: "Sign Up Form" },
  { value: "Statistics", label: "Statistics" },
  { value: "Cart", label: "Cart" },
  { value: "Checkout", label: "Checkout" },
  { value: "Features Section", label: "Features Section" },
  { value: "Newsletter Section", label: "Newsletter Section" },
  { value: "Contacts", label: "Contacts" },
  { value: "Team", label: "Team" },
  { value: "Partners", label: "Partners" },
  { value: "About", label: "About" },
  { value: "Icon", label: "Icon" },
  { value: "Inspiration", label: "Inspiration" },
  { value: "Font", label: "Font" },
  { value: "Music", label: "Music" },
  { value: "AI", label: "AI" },
  { value: "Wireframe", label: "Wireframe" },
  { value: "Sketch", label: "Sketch" },
  { value: "Prototype", label: "Prototype" },
  { value: "Accessibility", label: "Accessibility" },
  { value: "Course", label: "Course" },
  { value: "PWA", label: "PWA" },
  { value: "Blog", label: "Blog" },
  { value: "Optimization", label: "Optimization" },
  { value: "Test", label: "Test" },
  { value: "Development", label: "Development" },
  { value: "Web", label: "Web" },
  { value: "Meta Tags", label: "Meta Tags" },
  { value: "Interface", label: "Interface" },
  { value: "Extension", label: "Extension" },
  { value: "Performance", label: "Performance" },
  { value: "API", label: "API" },
  { value: "Architecture", label: "Architecture" },
  { value: "Documentation", label: "Documentation" },
  { value: "Structured Data", label: "Structured Data" },
  { value: "README", label: "README" },
  { value: "Browser", label: "Browser" },
  { value: "UIDesign", label: "UIDesign" },
  { value: "React.js", label: "React.js" },
  { value: "Code", label: "Code" },
  { value: "Marketing", label: "Marketing" },
  { value: "IOS", label: "IOS" },
  { value: "Adobe XD", label: "Adobe XD" },
  { value: "Android", label: "Android" },
  { value: "Google", label: "Google" },
  { value: "Flutter", label: "Flutter" },
  { value: "Desktop", label: "Desktop" },
  { value: "Screen", label: "Screen" },
  { value: "Shortcut", label: "Shortcut" },
  { value: "NoCode", label: "NoCode" },
  { value: "Gradient Color", label: "Gradient Color" },
  { value: "Logo", label: "Logo" },
  { value: "illustration", label: "illustration" },
  { value: "Collection", label: "Collection" },
  { value: "Neumorphism", label: "Neumorphism" },
  { value: "Claymorphism", label: "Claymorphism" },
  { value: "Animation", label: "Animation" },
  { value: "Brand", label: "Brand" },
  { value: "Business", label: "Business" },
  { value: "Responsive", label: "Responsive" },
  { value: "VS Code Tool", label: "VS Code Tool" },
  { value: "GitHub", label: "GitHub" },
  { value: "JSON", label: "JSON" },
  { value: "QR Code", label: "QR Code" },
  { value: "Vue.js", label: "Vue.js" },
  { value: "Bootstrap", label: "Bootstrap" },
  { value: "Awesome", label: "Awesome" },
  { value: "Database", label: "Database" },
  { value: "Library", label: "Library" },
  { value: "3D Image", label: "3D Image" },
  { value: "Emoji", label: "Emoji" },
  { value: "Pattern", label: "Pattern" },
  { value: "Social Media", label: "Social Media" },
  { value: "GIF", label: "GIF" },
  { value: "Blob", label: "Blob" },
  { value: "Wave", label: "Wave" },
  //   Designer
  { value: "Designer", label: "Designer", isDisabled: true },
  { value: "User Reasercher", label: "User Reasercher" },
  { value: "Visual Designer", label: "Visual Designer" },
  { value: "Creative Director", label: "Creative Director" },
  { value: "Graphic Designer", label: "Graphic Designer" },
  { value: "Design Manager", label: "Design Manager" },
  //   Product
  { value: "Product", label: "Product", isDisabled: true },
  { value: "Product Manager", label: "Product Manager" },
  //   Operations
  { value: "Operations", label: "Operations", isDisabled: true },
  { value: "Finance / Accounting", label: "Finance / Accounting" },
  { value: "H.R", label: "H.R" },
  { value: "Office Manager", label: "Office Manager" },
  { value: "User", label: "User" },
  { value: "Customer Service", label: "Customer Service" },
  { value: "Operations Manager", label: "Operations Manager" },
  { value: "Chief of Staff", label: "Chief of Staff" },
  //   Sales
  { value: "Sales", label: "Sales", isDisabled: true },
  { value: "Business Development", label: "Business Development" },
  {
    value: "Sales Development Representative",
    label: "Sales Development Representative",
  },
  { value: "Account Executive", label: "Account Executive" },
  { value: "BD Manager", label: "BD Manager" },
  { value: "Account Manager", label: "Account Manager" },
  { value: "Sales Manager", label: "Sales Manager" },
  { value: "Customer Success Manager", label: "Customer Success Manager" },
  //   Marketing
  { value: "Marketing", label: "Marketing", isDisabled: true },
  { value: "Growth Hacker", label: "Growth Hacker" },
  { value: "Marketing Manager", label: "Marketing Manager" },
  { value: "Digital Marketing Manager", label: "Digital Marketing Manager" },
  { value: "Content Creator", label: "Content Creator" },
  { value: "Product Marketing Manager", label: "Product Marketing Manager" },
  { value: "Social Media Manager", label: "Social Media Manager" },
  { value: "Copywriter", label: "Copywriter" },
  //   Backend
  { value: "Management", label: "Management", isDisabled: true },
  { value: "CEO", label: "CEO" },
  { value: "CFO", label: "CFO" },
  { value: "CMO", label: "CMO" },
  { value: "COO", label: "COO" },
  { value: "CTO", label: "CTO" },
  //   Mobile
  { value: "Other Engineering", label: "Other Engineering", isDisabled: true },
  { value: "Hardware Engineer", label: "Hardware Engineer" },
  { value: "Mechanical Engineer", label: "Mechanical Engineer" },
  { value: "Systems Engineer", label: "Systems Engineer" },
  //   Algorithms
  { value: "Other", label: "Other", isDisabled: true },
  { value: "Business Analyst", label: "Business Analyst" },
  { value: "Project Manager", label: "Project Manager" },
  { value: "Attorney", label: "Attorney" },
  { value: "Data Analyst", label: "Data Analyst" },
  //   Data Science
  { value: "Other", label: "Other", isDisabled: true },
  { value: "Business Analyst", label: "Business Analyst" },
  { value: "Project Manager", label: "Project Manager" },
  { value: "Attorney", label: "Attorney" },
  { value: "Data Analyst", label: "Data Analyst" },
  //   Cyber Security
  { value: "Other", label: "Other", isDisabled: true },
  { value: "Business Analyst", label: "Business Analyst" },
  { value: "Project Manager", label: "Project Manager" },
  { value: "Attorney", label: "Attorney" },
  { value: "Data Analyst", label: "Data Analyst" },
];

export const CategoryOptions = [
  { value: "Frontend", label: "Frontend" },
  { value: "Backend", label: "Backend" },
  { value: "Mobile", label: "Mobile" },
  { value: "Artificial Intelligence", label: "Artificial Intelligence" },
  { value: "Algorithms", label: "Algorithms" },
  { value: "IT Courses", label: "IT Courses" },
  { value: "Cyber Security", label: "Cyber Security" },
];

export const MobileOptions = [
  { value: "Mobile", label: "Mobile", isDisabled: true },
  { value: "Python", label: "Python" },
  { value: "JavaScript", label: "JavaScript" },
  { value: "Java", label: "Java" },
  { value: "Go", label: "Go" },
  { value: "C++", label: "C++" },
  { value: "PHP", label: "PHP" },
];
export const AIOptions = [
  { value: "AI", label: "AI", isDisabled: true },
  { value: "Python", label: "Python" },
  { value: "JavaScript", label: "JavaScript" },
  { value: "Java", label: "Java" },
  { value: "Go", label: "Go" },
  { value: "C++", label: "C++" },
  { value: "PHP", label: "PHP" },
];
export const SecurityOptions = [
  { value: "Cyber Security", label: "Cyber Security", isDisabled: true },
  { value: "Python", label: "Python" },
  { value: "JavaScript", label: "JavaScript" },
  { value: "Java", label: "Java" },
  { value: "Go", label: "Go" },
  { value: "C++", label: "C++" },
  { value: "PHP", label: "PHP" },
];

export const BackendOptions = [
  { value: "Backend", label: "Backend", isDisabled: true },
  { value: "Python", label: "Python" },
  { value: "JavaScript", label: "JavaScript" },
  { value: "Java", label: "Java" },
  { value: "Go", label: "Go" },
  { value: "C++", label: "C++" },
  { value: "PHP", label: "PHP" },
  { value: "Swift", label: "Swift" },
  { value: "Ruby", label: "Ruby" },
  { value: "Rust", label: "Rust" },
  { value: "Kotlin", label: "Kotlin" },
  { value: "MySQL", label: "MySQL" },
  { value: "MongoDB", label: "MongoDB" },
  { value: "DynamoDB", label: "DynamoDB" },
  { value: "Redis", label: "Redis" },
  { value: "SQLlite", label: "SQLlite" },
  { value: "TypeScript", label: "TypeScript" },
  { value: "Perl", label: "Perl" },
  { value: "Matlab", label: "Matlab" },
  { value: "Lua", label: "Lua" },
  { value: "Ada", label: "Ada" },
  { value: "Fortran", label: "Fortran" },
  { value: "Dart", label: "Dart" },
  { value: "Flutter", label: "Flutter" },
  { value: "Scala", label: "Scala" },
  { value: "Node.js", label: "Node.js" },
  { value: "React.js", label: "React.js" },
  { value: "CI/CD", label: "CI/CD" },
  { value: "Adobe XD", label: "Adobe XD" },
  { value: "InVision Studio", label: "InVision Studio" },
  { value: "Zeplin", label: "Zeplin" },
  { value: "Adobe Photoshop", label: "Adobe Photoshop" },
  { value: "Adobe Illustrator", label: "Adobe Illustrator" },
  { value: "Sketch", label: "Sketch" },
  { value: "Bootstrap", label: "Bootstrap" },
  { value: "Bulma", label: "Bulma" },
  { value: "Semantic UI", label: "Semantic UI" },
  { value: "Foundation", label: "Foundation" },
  { value: "Material-UI", label: "Material-UI" },
  { value: "Chakra UI", label: "Chakra UI" },
  { value: "Ant Design", label: "Ant Design" },
  { value: "UIKit", label: "UIKit" },
  { value: "Tailwind CSS", label: "Tailwind CSS" },
  {
    value: "BEM (Block Element Modifier)",
    label: "BEM (Block Element Modifier)",
  },
  { value: "Styled Components", label: "Styled Components" },
  { value: "Sass", label: "Sass" },
  { value: "Less", label: "Less" },
  { value: "PostCSS", label: "PostCSS" },
  { value: "CSS", label: "CSS" },
  { value: "Figma", label: "Figma" },
  { value: "Jenkins", label: "Jenkins" },
  { value: "GitLab CI/CD", label: "GitLab CI/CD" },
  { value: "CircleCI", label: "CircleCI" },
  { value: "Travis CI", label: "Travis CI" },
  { value: "GitHub Actions", label: "GitHub Actions" },
  { value: "TeamCity", label: "TeamCity" },
  { value: "Bamboo", label: "Bamboo" },
  { value: "Azure DevOps", label: "Azure DevOps" },
  { value: "Codeship", label: "Codeship" },
  { value: "Bitbucket Pipelines", label: "Bitbucket Pipelines" },
  { value: "GoCD", label: "GoCD" },
  { value: "Semaphore", label: "Semaphore" },
  { value: "Drone", label: "Drone" },
  { value: "Spinnaker", label: "Spinnaker" },
  { value: "AWS CodePipeline", label: "AWS CodePipeline" },
  { value: "Kubernetes", label: "Kubernetes" },
  { value: "Vagrant", label: "Vagrant" },
  { value: "Ansible", label: "Ansible" },
  { value: "Packer", label: "Packer" },
  { value: "VirtualBox", label: "VirtualBox" },
  { value: "AWS Elastic Beanstalk", label: "AWS Elastic Beanstalk" },
  {
    value: "Google Kubernetes Engine (GKE)",
    label: "Google Kubernetes Engine (GKE)",
  },
  {
    value: "Microsoft Azure Container Instances",
    label: "Microsoft Azure Container Instances",
  },
  { value: "Red Hat OpenShift", label: "Red Hat OpenShift" },
  { value: "Docker Swarm", label: "Docker Swarm" },
  { value: "Rancher", label: "Rancher" },
  { value: "Nomad", label: "Nomad" },
  { value: "LXC (Linux Containers)", label: "LXC (Linux Containers)" },
  { value: "Podman", label: "Podman" },
  { value: "Postman", label: "Postman" },
  { value: "Buildah", label: "Buildah" },
  { value: "NumPy", label: "NumPy" },
  { value: "Pandas", label: "Pandas" },
  { value: "Matplotlib", label: "Matplotlib" },
  { value: "Seaborn", label: "Seaborn" },
  { value: "Apache Hadoop", label: "Apache Hadoop" },
  { value: "Apache Spark", label: "Apache Spark" },
  { value: "SQL", label: "SQL" },
  { value: "Elasticsearch", label: "Elasticsearch" },
  { value: "Apache Kafka", label: "Apache Kafka" },
  { value: "Tableau", label: "Tableau" },
  { value: "Power BI", label: "Power BI" },
  { value: "D3.js", label: "D3.js" },
  { value: "R", label: "R" },
  { value: "Julia", label: "Julia" },
  { value: "Ruby on Rails", label: "Ruby on Rails" },
  { value: "ASP.NET", label: "ASP.NET" },
  { value: "Laravel", label: "Laravel" },
  { value: "Next.js", label: "Next.js" },
  { value: "Gatsby", label: "Gatsby" },
  { value: "React Native", label: "React Native" },
  { value: "Ionic", label: "Ionic" },
  { value: "Xamarin", label: "Xamarin" },
  { value: "TensorFlow", label: "TensorFlow" },
  { value: "PyTorch", label: "PyTorch" },
  { value: "scikit-learn", label: "scikit-learn" },
  { value: "Keras", label: "Keras" },
  { value: "MXNet", label: "MXNet" },
  { value: "Theano", label: "Theano" },
  { value: "Caffe", label: "Caffe" },
  { value: "Spark MLlib", label: "Spark MLlib" },
  { value: "Symfony", label: "Symfony" },
  { value: "CodeIgniter", label: "CodeIgniter" },
  { value: "CakePHP", label: "CakePHP" },
  { value: "Qt", label: "Qt" },
  { value: "Boost", label: "Boost" },
  { value: "Poco", label: "Poco" },
  { value: "CppCMS", label: "CppCMS" },
  { value: "Gin", label: "Gin" },
  { value: "Echo", label: "Echo" },
  { value: "Revel", label: "Revel" },
  { value: "Fiber", label: "Fiber" },
  { value: "Spring Boot", label: "Spring Boot" },
  { value: "Hibernate", label: "Hibernate" },
  { value: "Struts", label: "Struts" },
  { value: "JSF (JavaServer Faces)", label: "JSF (JavaServer Faces)" },
  { value: "Angular", label: "Angular" },
  { value: "Flask", label: "Flask" },
  { value: "Pyramid", label: "Pyramid" },
  { value: "FastAPI", label: "FastAPI" },
  { value: "CherryPy", label: "CherryPy" },
  { value: "AWS", label: "AWS" },
  { value: "Google Cloud Platform", label: "Google Cloud Platform" },
  { value: "Microsoft Azure", label: "Microsoft Azure" },
  { value: "Heroku", label: "Heroku" },
  { value: "Git", label: "Git" },
  { value: "GitHub", label: "GitHub" },
  { value: "Bitbucket", label: "Bitbucket" },
  { value: "JIRA", label: "JIRA" },
  { value: "Confluence", label: "Confluence" },
  { value: "Slack", label: "Slack" },
  { value: "Trello", label: "Trello" },
  { value: "Asana", label: "Asana" },
  { value: "Visual Studio Code", label: "Visual Studio Code" },
  { value: "Atom", label: "Atom" },
  { value: "Sublime Text", label: "Sublime Text" },
  { value: "IntelliJ IDEA", label: "IntelliJ IDEA" },
  { value: "PyCharm", label: "PyCharm" },
  { value: "Eclipse", label: "Eclipse" },
  { value: "NetBeans", label: "NetBeans" },
  { value: "Visual Studio", label: "Visual Studio" },
  { value: "Unity", label: "Unity" },
  { value: "Adobe Photoshop", label: "Adobe Photoshop" },
  { value: "Adobe Illustrator", label: "Adobe Illustrator" },
  { value: "Figma", label: "Figma" },
  { value: "Sketch", label: "Sketch" },
  { value: "Vue.js", label: "Vue.js" },
  { value: "C#", label: "C#" },
  { value: ".NET", label: ".NET" },
  { value: "Express.js", label: "Express.js" },
  { value: "Flask", label: "Flask" },
  { value: "Django", label: "Django" },
  { value: "Spring Boot", label: "Spring Boot" },
  { value: "Hibernate", label: "Hibernate" },
  { value: "PostgreSQL", label: "PostgreSQL" },
  { value: "Firebase", label: "Firebase" },
  { value: "Apache Kafka", label: "Apache Kafka" },
  { value: "Apache Spark", label: "Apache Spark" },
  { value: "Elasticsearch", label: "Elasticsearch" },
  { value: "Docker", label: "Docker" },
];

export const PricingOptions = [
  { value: "Free", label: "Free" },
  { value: "Paid", label: "Paid" },
  { value: "Freemium", label: "Freemium" },
  { value: "Free+Paid", label: "Free+Paid" },
];
