export const FrontendOptions = [
  { value: "Frontend", label: "Frontend", isDisabled: true },
  // Frontend Layouts
  { value: "contentlayout", label: "Content (lyt)" },
  { value: "footerlayout", label: "Footer (lyt)" },
  { value: "formslayout", label: "Forms (lyt)" },
  { value: "headerlayout", label: "Header (lyt)" },
  { value: "herolayout", label: "Hero (lyt)" },
  { value: "navbarlayout", label: "Navbar (lyt)" },

  // Frontend Components
  { value: "Components", label: "Components" },
  { value: "buttoncomp", label: "Button (comp)" },
  { value: "carouselcomp", label: "Carousel (comp)" },
  { value: "checkboxcomp", label: "Checkbox (comp)" },
  { value: "countdowncomp", label: "Countdown (comp)" },
  { value: "datepickercomp", label: "Datepicker (comp)" },
  { value: "fileinputcomp", label: "File Input (comp)" },
  { value: "inputfieldcomp", label: "Input Field (comp)" },
  { value: "loadercomp", label: "Loader (comp)" },
  { value: "radiocomp", label: "Radio (comp)" },
  { value: "rangeslidercomp", label: "Range Slider (comp)" },
  { value: "selectcomp", label: "Select (comp)" },
  { value: "spinnercomp", label: "Spinner (comp)" },
  { value: "textareacomp", label: "Textarea (comp)" },
  { value: "togglecomp", label: "Toggle (comp)" },
  { value: "tooltipscomp", label: "Tooltips (comp)" },

  // Frontend Sections
  { value: "Sections", label: "Sections" },
  // AAAA
  { value: "aboutsection", label: "About (sec)" },
  { value: "accordionsection", label: "Accordion (sec)" },
  { value: "alertsection", label: "Alert (sec)" },
  { value: "applicationshellsection", label: "Application Shell (sec)" },
  { value: "avatarsection", label: "Avatar (sec)" },
  // BBBB
  { value: "badgessection", label: "Badges (sec)" },
  { value: "bannersection", label: "Banner (sec)" },
  { value: "blockquotesection", label: "Blockquote (sec)" },
  { value: "blogsection", label: "Blog (sec)" },
  { value: "bottomnavigationsection", label: "Bottom Navigation (sec)" },
  { value: "breadcrumbssection", label: "Breadcrumbs (sec)" },
  { value: "buttongroupsection", label: "Button Group (sec)" },
  // CCCC
  { value: "cardssection", label: "Cards (sec)" },
  { value: "cartsection", label: "Cart (sec)" },
  { value: "checkoutsection", label: "Checkout (sec)" },
  { value: "commentssection", label: "Comments (sec)" },
  { value: "contactssection", label: "Contacts (sec)" },
  { value: "cookiesection", label: "Cookie (sec)" },
  { value: "ctasection", label: "CTA (sec)" },
  // DDDD
  { value: "devicemockupsection", label: "Device Mockup (sec)" },
  { value: "dividersection", label: "Divider (sec)" },
  { value: "draweroffcanvassection", label: "Drawer (offcanvas) (sec)" },
  { value: "dropdownfiltersection", label: "Dropdown Filter (sec)" },
  { value: "dropdownsection", label: "Dropdown (sec)" },
  // EEEE
  { value: "errorBarsection", label: "ErrorBar (sec)" },
  // FFFF
  { value: "fAQsection", label: "FAQ (sec)" },
  { value: "featuressection", label: "Features (sec)" },
  { value: "floatinglabelsection", label: "Floating Label (sec)" },
  // GGGG
  { value: "gallerysection", label: "Gallery (sec)" },
  // HHHH
  {
    value: "horizontallinesection",
    label: "horizontal Line (HR) (sec)",
  },
  // IIII
  { value: "imagesection", label: "Image (sec)" },
  { value: "indicatorssection", label: "Indicators (sec)" },
  // JJJJ
  { value: "jumbotronsection", label: "Jumbotron (sec)" },
  // KKKK
  { value: "kbdkeyboardsection", label: "KBD (Keyboard) (sec)" },
  // LLLL
  { value: "linksection", label: "Link (sec)" },
  { value: "listgroupsection", label: "List Group (sec)" },
  { value: "listsection", label: "List (sec)" },
  { value: "loginformsection", label: "Login Form (sec)" },
  { value: "logoutformsection", label: "Logout Form (sec)" },
  // MMMM
  { value: "megamenusection", label: "Mega Menu (sec)" },
  { value: "menusection", label: "Menu (sec)" },
  { value: "modalsection", label: "Modal (sec)" },
  // NNNN
  { value: "newslettersection", label: "Newsletter (sec)" },
  // OOOO
  // PPPP
  { value: "paginationsection", label: "Pagination (sec)" },
  { value: "paragraphsection", label: "Paragraph (sec)" },
  { value: "partnerssection", label: "Partners (sec)" },
  { value: "popoversection", label: "Popover (sec)" },
  { value: "popupsection", label: "Popup (sec)" },
  { value: "pricingsection", label: "Pricing (sec)" },
  { value: "progressbarsection", label: "Progress bar (sec)" },
  // QQQQ
  // RRRR
  { value: "ratingsection", label: "Rating (sec)" },
  // SSSS
  { value: "searchinputsection", label: "Search Input (sec)" },
  { value: "sidebarsection", label: "Sidebar (sec)" },
  { value: "sidenavigationsection", label: "Side Navigation (sec)" },
  { value: "signupformsection", label: "Sign Up Form (sec)" },
  { value: "skeletonsection", label: "Skeleton (sec)" },
  { value: "speeddailsection", label: "Speed Dail (sec)" },
  { value: "stacksection", label: "Stack (sec)" },
  { value: "statisticssection", label: "Statistics (sec)" },
  { value: "stepperssection", label: "Steppers (sec)" },
  { value: "stepssection", label: "Steps (sec)" },
  { value: "stickybannersection", label: "Sticky Banner (sec)" },
  { value: "swapsection", label: "Swap (sec)" },
  // TTTT
  { value: "tableheadersection", label: "Table Header (sec)" },
  { value: "tablesection", label: "Table (sec)" },
  { value: "tabssection", label: "Tabs (sec)" },
  { value: "teamsection", label: "Team (sec)" },
  { value: "testimonialsection", label: "Testimonial (sec)" },
  { value: "textsection", label: "Text (sec)" },
  { value: "timelinesection", label: "Timeline (sec)" },
  { value: "toastsection", label: "Toast (sec)" },
  // VVVV
  { value: "videosection", label: "Video (sec)" },

  // Frontend Development
  { value: "Accessibility", label: "Accessibility" },
  { value: "Architecture", label: "Architecture" },
  { value: "Chrome DevTool", label: "Chrome DevTool" },
  { value: "Code", label: "Code" },
  { value: "Database", label: "Database" },
  { value: "Development", label: "Development" },
  { value: "Documentation", label: "Documentation" },
  { value: "JSON", label: "JSON" },
  { value: "Meta Tags", label: "Meta Tags" },
  { value: "Optimization", label: "Optimization" },
  { value: "Performance", label: "Performance" },
  { value: "Responsive", label: "Responsive" },
  { value: "Privacy", label: "Privacy" },
  { value: "PWA", label: "PWA" },
  { value: "QR Code", label: "QR Code" },
  { value: "SEO", label: "SEO" },
  { value: "Shortcut", label: "Shortcut" },
  { value: "SSR", label: "Server Sided Rendering (SSR)" },
  { value: "Structured Data", label: "Structured Data" },
  { value: "Test", label: "Test" },
  { value: "Web", label: "Web" },

  // Frontend Library
  { value: "Library", label: "Library" },
  { value: "WebRTC", label: "WebRTC" }, // Think of smth for this kind of libraries
  { value: "Angular.js", label: "Angular.js" },
  { value: "Next.js", label: "Next.js" },
  { value: "Nuxt.js", label: "Nuxt.js" },
  { value: "React.js", label: "React.js" },
  { value: "Vue.js", label: "Vue.js" },
  //   { value: "Redux", label: "Redux" }, // Also do the same with redux create tag called "State Management" put redux to it
  //   { value: "D3.js", label: "D3.js" }, // because d3.js is not big enough just create tag called graphs libray and put d3.js to it
  //   { value: "Zeplin", label: "Zeplin" },
  //   { value: "Bulma", label: "Bulma" },
  //   { value: "Semantic UI", label: "Semantic UI" }, // For all the ui component producing website 1 tag name
  //   { value: "Gatsby", label: "Gatsby" }, // "UI Components collection" then these components web link appears
  //   { value: "Material-UI", label: "Material-UI" },
  //   { value: "Chakra UI", label: "Chakra UI" },

  // Frontend UI/UX Design
  { value: "UIDesign", label: "UIDesign" },
  { value: "Icon", label: "Icon" },
  { value: "Video", label: "Video" },
  { value: "Picture", label: "Picture" },
  { value: "Color", label: "Color" },
  { value: "Gradient Color", label: "Gradient Color" },
  { value: "illustration", label: "illustration" },
  { value: "Inspiration", label: "Inspiration" },
  { value: "Typography", label: "Typography" },
  { value: "Font", label: "Font" },
  { value: "Music", label: "Music" },
  { value: "Animation", label: "Animation" },
  { value: "Pattern", label: "Pattern" },
  { value: "Blob", label: "Blob" },
  { value: "Wave", label: "Wave" },
  { value: "Emoji", label: "Emoji" },

  { value: "Interface", label: "Interface" },
  { value: "IOS", label: "IOS" },
  { value: "Android", label: "Android" },
  { value: "Google", label: "Google" },
  { value: "Desktop", label: "Desktop" },
  { value: "Screen", label: "Screen" },
  { value: "Awesome", label: "Awesome" },
  { value: "3D Image", label: "3D Image" },
  { value: "Social Media", label: "Social Media" },
  { value: "GIF", label: "GIF" },
  { value: "Template", label: "Template" },
  { value: "Wireframe", label: "Wireframe" },
  { value: "Logo", label: "Logo" },
  { value: "Prototype", label: "Prototype" },

  // Frontend Tools
  { value: "DesignTools", label: "DesignTools" },
  { value: "Adobe Illustrator", label: "Adobe Illustrator" }, // prototyping
  { value: "Adobe Photoshop", label: "Adobe Photoshop" },
  { value: "Adobe XD", label: "Adobe XD" },
  { value: "Sketch", label: "Sketch" },
  { value: "Figma", label: "Figma" },
  { value: "CSS", label: "CSS" }, // ui design code
  { value: "Bootstrap", label: "Bootstrap" },
  { value: "Sass", label: "Sass" },
  { value: "PostCSS", label: "PostCSS" },
  { value: "TailwindCSS", label: "TailwindCSS" },
  { value: "Less", label: "Less" },
  { value: "Styled Components", label: "Styled Components" },
  { value: "Generators", label: "Generators" },
  { value: "HTML", label: "HTML" },
  { value: "AI", label: "AI" },
  { value: "Extension", label: "Extension" },
  { value: "API", label: "API" },
  { value: "Browser", label: "Browser" },
  { value: "NoCode", label: "NoCode" },
  { value: "VS Code Tool", label: "VS Code Tool" },
  { value: "InVision Studio", label: "InVision Studio" },

  // Frontend Mixed
  { value: "Marketing", label: "Marketing" },
  { value: "Business", label: "Business" },
  { value: "Brand", label: "Brand" },
  { value: "Collection", label: "Collection" },
  { value: "Ant Design", label: "Ant Design" },
  { value: "Neumorphism", label: "Neumorphism" },
  { value: "Claymorphism", label: "Claymorphism" },
  { value: "Glassmorphism", label: "Glassmorphism" },
  { value: "GitHub", label: "GitHub" },

  //   Designer
  { value: "Designer", label: "Designer", isDisabled: true },
  { value: "User Reasercher", label: "User Reasercher" },
  { value: "Visual Designer", label: "Visual Designer" },
  { value: "Creative Director", label: "Creative Director" },
  { value: "Graphic Designer", label: "Graphic Designer" },
  { value: "Design Manager", label: "Design Manager" },
];

// { value: "SVG", label: "SVG" },
// { value: "PNG", label: "PNG" },
// { value: "JPEG", label: "JPEG" },
// { value: "GIF", label: "GIF" },
// { value: "JPG", label: "JPG" },

// { value: "TensorFlow", label: "TensorFlow" },
// { value: "PyTorch", label: "PyTorch" },
// { value: "scikit-learn", label: "scikit-learn" },
// { value: "Keras", label: "Keras" },
// { value: "MXNet", label: "MXNet" },
// { value: "Theano", label: "Theano" },
// { value: "Caffe", label: "Caffe" },
// //   Team Management
// { value: "JIRA", label: "JIRA" },
// { value: "Confluence", label: "Confluence" },
// { value: "Slack", label: "Slack" },
// { value: "Trello", label: "Trello" },
// { value: "Asana", label: "Asana" },
// { value: "Discord", label: "Discord" },
// { value: "React Native", label: "React Native" },
// { value: "Ionic", label: "Ionic" },
// { value: "Xamarin", label: "Xamarin" },
// { value: "Tableau", label: "Tableau" },
// { value: "Power BI", label: "Power BI" },
// { value: "R", label: "R" },
// { value: "Julia", label: "Julia" },
// { value: "Buildah", label: "Buildah" },
// { value: "NumPy", label: "NumPy" },
// { value: "Pandas", label: "Pandas" },
// { value: "Matplotlib", label: "Matplotlib" },
// { value: "Seaborn", label: "Seaborn" },

// export const sdafsdsdf = [
//     { value: "Frontend", label: "Frontend", isDisabled: true },
//     // Frontend Layouts
//     { value: "contentlayout", label: "Content (lyt)" },
//     { value: "footerlayout", label: "Footer (lyt)" },
//     { value: "formslayout", label: "Forms (lyt)" },
//     { value: "headerlayout", label: "Header (lyt)" },
//     { value: "herolayout", label: "Hero (lyt)" },
//     { value: "navbarlayout", label: "Navbar (lyt)" },

//     // Frontend Components
//     { value: "Components", label: "Components" },
//     { value: "buttoncomp", label: "Button (comp)" },
//     { value: "carouselcomp", label: "Carousel (comp)" },
//     { value: "checkboxcomp", label: "Checkbox (comp)" },
//     { value: "countdowncomp", label: "Countdown (comp)" },
//     { value: "datepickercomp", label: "Datepicker (comp)" },
//     { value: "fileinputcomp", label: "File Input (comp)" },
//     { value: "inputfieldcomp", label: "Input Field (comp)" },
//     { value: "loadercomp", label: "Loader (comp)" },
//     { value: "radiocomp", label: "Radio (comp)" },
//     { value: "rangeslidercomp", label: "Range Slider (comp)" },
//     { value: "selectcomp", label: "Select (comp)" },
//     { value: "spinnercomp", label: "Spinner (comp)" },
//     { value: "textareacomp", label: "Textarea (comp)" },
//     { value: "togglecomp", label: "Toggle (comp)" },
//     { value: "tooltipscomp", label: "Tooltips (comp)" },

//     // Frontend Sections
//     { value: "Sections", label: "Sections" },
//     // AAAA
//     { value: "About Section", label: "About (sec)" },
//     { value: "Accordion Section", label: "Accordion (sec)" },
//     { value: "Alert Section", label: "Alert (sec)" },
//     { value: "Application Shell Section", label: "Application Shell (sec)" },
//     { value: "Avatar Section", label: "Avatar (sec)" },
//     // BBBB
//     { value: "Badges Section", label: "Badges (sec)" },
//     { value: "Banner Section", label: "Banner (sec)" },
//     { value: "Blockquote Section", label: "Blockquote (sec)" },
//     { value: "Blog Section", label: "Blog (sec)" },
//     { value: "Bottom Navigation Section", label: "Bottom Navigation (sec)" },
//     { value: "Breadcrumbs Section", label: "Breadcrumbs (sec)" },
//     { value: "Button Group Section", label: "Button Group (sec)" },
//     // CCCC
//     { value: "Cards Section", label: "Cards (sec)" },
//     { value: "Cart Section", label: "Cart (sec)" },
//     { value: "Checkout Section", label: "Checkout (sec)" },
//     { value: "Comments Section", label: "Comments (sec)" },
//     { value: "Contacts Section", label: "Contacts (sec)" },
//     { value: "Cookie Section", label: "Cookie (sec)" },
//     { value: "CTA Section", label: "CTA (sec)" },
//     // DDDD
//     { value: "Device Mockup Section", label: "Device Mockup (sec)" },
//     { value: "Divider Section", label: "Divider (sec)" },
//     { value: "Drawer (offcanvas) Section", label: "Drawer (offcanvas) (sec)" },
//     { value: "Dropdown Filter Section", label: "Dropdown Filter (sec)" },
//     { value: "Dropdown Section", label: "Dropdown (sec)" },
//     // EEEE
//     { value: "ErrorBar Section", label: "ErrorBar (sec)" },
//     // FFFF
//     { value: "FAQ Section", label: "FAQ (sec)" },
//     { value: "Features Section", label: "Features (sec)" },
//     { value: "Floating Label Section", label: "Floating Label (sec)" },
//     // GGGG
//     { value: "Gallery Section", label: "Gallery (sec)" },
//     // HHHH
//     {
//       value: "Horizontal Line (HR) Section",
//       label: "Horizontal Line (HR) (sec)",
//     },
//     // IIII
//     { value: "Image Section", label: "Image (sec)" },
//     { value: "Indicators Section", label: "Indicators (sec)" },
//     // JJJJ
//     { value: "Jumbotron Section", label: "Jumbotron (sec)" },
//     // KKKK
//     { value: "KBD (Keyboard) Section", label: "KBD (Keyboard) (sec)" },
//     // LLLL
//     { value: "Link Section", label: "Link (sec)" },
//     { value: "List Group Section", label: "List Group (sec)" },
//     { value: "List Section", label: "List (sec)" },
//     { value: "Login Form Section", label: "Login Form (sec)" },
//     { value: "Logout Form Section", label: "Logout Form (sec)" },
//     // MMMM
//     { value: "Mega Menu Section", label: "Mega Menu (sec)" },
//     { value: "Menu Section", label: "Menu (sec)" },
//     { value: "Modal Section", label: "Modal (sec)" },
//     // NNNN
//     { value: "Newsletter Section", label: "Newsletter (sec)" },
//     // OOOO
//     // PPPP
//     { value: "Pagination Section", label: "Pagination (sec)" },
//     { value: "Paragraph Section", label: "Paragraph (sec)" },
//     { value: "Partners Section", label: "Partners (sec)" },
//     { value: "Popover Section", label: "Popover (sec)" },
//     { value: "Popup Section", label: "Popup (sec)" },
//     { value: "Pricing Section", label: "Pricing (sec)" },
//     { value: "Progress bar Section", label: "Progress bar (sec)" },
//     // QQQQ
//     // RRRR
//     { value: "Rating Section", label: "Rating (sec)" },
//     // SSSS
//     { value: "searchinput Section", label: "Search Input (sec)" },
//     { value: "Sidebar Section", label: "Sidebar (sec)" },
//     { value: "Side Navigation Section", label: "Side Navigation (sec)" },
//     { value: "Sign Up Form Section", label: "Sign Up Form (sec)" },
//     { value: "Skeleton Section", label: "Skeleton (sec)" },
//     { value: "Speed Dail Section", label: "Speed Dail (sec)" },
//     { value: "Stack Section", label: "Stack (sec)" },
//     { value: "Statistics Section", label: "Statistics (sec)" },
//     { value: "Steppers Section", label: "Steppers (sec)" },
//     { value: "Steps Section", label: "Steps (sec)" },
//     { value: "Sticky Banner Section", label: "Sticky Banner (sec)" },
//     { value: "Swap Section", label: "Swap (sec)" },
//     // TTTT
//     { value: "Table Header Section", label: "Table Header (sec)" },
//     { value: "Table Section", label: "Table (sec)" },
//     { value: "Tabs Section", label: "Tabs (sec)" },
//     { value: "Team Section", label: "Team (sec)" },
//     { value: "Testimonial Section", label: "Testimonial (sec)" },
//     { value: "Text Section", label: "Text (sec)" },
//     { value: "Timeline Section", label: "Timeline (sec)" },
//     { value: "Toast Section", label: "Toast (sec)" },
//     // VVVV
//     { value: "Video Section", label: "Video (sec)" },

//     // Frontend Development
//     { value: "Accessibility", label: "Accessibility" },
//     { value: "Architecture", label: "Architecture" },
//     { value: "Chrome DevTool", label: "Chrome DevTool" },
//     { value: "Code", label: "Code" },
//     { value: "Database", label: "Database" },
//     { value: "Development", label: "Development" },
//     { value: "Documentation", label: "Documentation" },
//     { value: "JSON", label: "JSON" },
//     { value: "Meta Tags", label: "Meta Tags" },
//     { value: "Optimization", label: "Optimization" },
//     { value: "Performance", label: "Performance" },
//     { value: "Responsive", label: "Responsive" },
//     { value: "Privacy", label: "Privacy" },
//     { value: "PWA", label: "PWA" },
//     { value: "QR Code", label: "QR Code" },
//     { value: "SEO", label: "SEO" },
//     { value: "Shortcut", label: "Shortcut" },
//     { value: "SSR", label: "Server Sided Rendering (SSR)" },
//     { value: "Structured Data", label: "Structured Data" },
//     { value: "Test", label: "Test" },
//     { value: "Web", label: "Web" },

//     // Frontend Library
//     { value: "Library", label: "Library" },
//     { value: "WebRTC", label: "WebRTC" }, // Think of smth for this kind of libraries
//     { value: "Angular.js", label: "Angular.js" },
//     { value: "Next.js", label: "Next.js" },
//     { value: "Nuxt.js", label: "Nuxt.js" },
//     { value: "React.js", label: "React.js" },
//     { value: "Vue.js", label: "Vue.js" },
//     //   { value: "Redux", label: "Redux" }, // Also do the same with redux create tag called "State Management" put redux to it
//     //   { value: "D3.js", label: "D3.js" }, // because d3.js is not big enough just create tag called graphs libray and put d3.js to it
//     //   { value: "Zeplin", label: "Zeplin" },
//     //   { value: "Bulma", label: "Bulma" },
//     //   { value: "Semantic UI", label: "Semantic UI" }, // For all the ui component producing website 1 tag name
//     //   { value: "Gatsby", label: "Gatsby" }, // "UI Components collection" then these components web link appears
//     //   { value: "Material-UI", label: "Material-UI" },
//     //   { value: "Chakra UI", label: "Chakra UI" },

//     // Frontend UI/UX Design
//     { value: "UIDesign", label: "UIDesign" },
//     { value: "Icon", label: "Icon" },
//     { value: "Video", label: "Video" },
//     { value: "Picture", label: "Picture" },
//     { value: "Color", label: "Color" },
//     { value: "Gradient Color", label: "Gradient Color" },
//     { value: "illustration", label: "illustration" },
//     { value: "Inspiration", label: "Inspiration" },
//     { value: "Typography", label: "Typography" },
//     { value: "Font", label: "Font" },
//     { value: "Music", label: "Music" },
//     { value: "Animation", label: "Animation" },
//     { value: "Pattern", label: "Pattern" },
//     { value: "Blob", label: "Blob" },
//     { value: "Wave", label: "Wave" },
//     { value: "Emoji", label: "Emoji" },

//     { value: "Interface", label: "Interface" },
//     { value: "IOS", label: "IOS" },
//     { value: "Android", label: "Android" },
//     { value: "Google", label: "Google" },
//     { value: "Desktop", label: "Desktop" },
//     { value: "Screen", label: "Screen" },
//     { value: "Awesome", label: "Awesome" },
//     { value: "3D Image", label: "3D Image" },
//     { value: "Social Media", label: "Social Media" },
//     { value: "GIF", label: "GIF" },
//     { value: "Template", label: "Template" },
//     { value: "Wireframe", label: "Wireframe" },
//     { value: "Logo", label: "Logo" },
//     { value: "Prototype", label: "Prototype" },

//     // Frontend Tools
//     { value: "DesignTools", label: "DesignTools" },
//     { value: "Adobe Illustrator", label: "Adobe Illustrator" }, // prototyping
//     { value: "Adobe Photoshop", label: "Adobe Photoshop" },
//     { value: "Adobe XD", label: "Adobe XD" },
//     { value: "Sketch", label: "Sketch" },
//     { value: "Figma", label: "Figma" },
//     { value: "CSS", label: "CSS" }, // ui design code
//     { value: "Bootstrap", label: "Bootstrap" },
//     { value: "Sass", label: "Sass" },
//     { value: "PostCSS", label: "PostCSS" },
//     { value: "TailwindCSS", label: "TailwindCSS" },
//     { value: "Less", label: "Less" },
//     { value: "Styled Components", label: "Styled Components" },
//     { value: "Generators", label: "Generators" },
//     { value: "HTML", label: "HTML" },
//     { value: "AI", label: "AI" },
//     { value: "Extension", label: "Extension" },
//     { value: "API", label: "API" },
//     { value: "Browser", label: "Browser" },
//     { value: "NoCode", label: "NoCode" },
//     { value: "VS Code Tool", label: "VS Code Tool" },
//     { value: "InVision Studio", label: "InVision Studio" },

//     // Frontend Mixed
//     { value: "Marketing", label: "Marketing" },
//     { value: "Business", label: "Business" },
//     { value: "Brand", label: "Brand" },
//     { value: "Collection", label: "Collection" },
//     { value: "Ant Design", label: "Ant Design" },
//     { value: "Neumorphism", label: "Neumorphism" },
//     { value: "Claymorphism", label: "Claymorphism" },
//     { value: "Glassmorphism", label: "Glassmorphism" },
//     { value: "GitHub", label: "GitHub" },

//     //   Designer
//     { value: "Designer", label: "Designer", isDisabled: true },
//     { value: "User Reasercher", label: "User Reasercher" },
//     { value: "Visual Designer", label: "Visual Designer" },
//     { value: "Creative Director", label: "Creative Director" },
//     { value: "Graphic Designer", label: "Graphic Designer" },
//     { value: "Design Manager", label: "Design Manager" },
//   ];
