export const FrontendOptions = [
  { value: "Frontend", label: "Frontend", isDisabled: true },
  // Frontend Layouts
  { value: "contentlayout", label: "Content (lyt)" },
  { value: "footerlayout", label: "Footer (lyt)" },
  { value: "formslayout", label: "Forms (lyt)" },
  { value: "headerlayout", label: "Header (lyt)" },
  { value: "herolayout", label: "Hero (lyt)" },
  { value: "navbarlayout", label: "Navbar (lyt)" },

  // Frontend Components
  { value: "Components", label: "Components" },
  { value: "buttoncomp", label: "Button (comp)" },
  { value: "carouselcomp", label: "Carousel (comp)" },
  { value: "checkboxcomp", label: "Checkbox (comp)" },
  { value: "countdowncomp", label: "Countdown (comp)" },
  { value: "datepickercomp", label: "Datepicker (comp)" },
  { value: "fileinputcomp", label: "File Input (comp)" },
  { value: "inputfieldcomp", label: "Input Field (comp)" },
  { value: "loadercomp", label: "Loader (comp)" },
  { value: "radiocomp", label: "Radio (comp)" },
  { value: "rangeslidercomp", label: "Range Slider (comp)" },
  { value: "selectcomp", label: "Select (comp)" },
  { value: "spinnercomp", label: "Spinner (comp)" },
  { value: "textareacomp", label: "Textarea (comp)" },
  { value: "togglecomp", label: "Toggle (comp)" },
  { value: "tooltipscomp", label: "Tooltips (comp)" },

  // Frontend Sections
  { value: "Sections", label: "Sections" },
  // AAAA
  { value: "aboutsection", label: "About (sec)" },
  { value: "accordionsection", label: "Accordion (sec)" },
  { value: "alertsection", label: "Alert (sec)" },
  { value: "applicationshellsection", label: "Application Shell (sec)" },
  { value: "avatarsection", label: "Avatar (sec)" },
  // BBBB
  { value: "badgessection", label: "Badges (sec)" },
  { value: "bannersection", label: "Banner (sec)" },
  { value: "blockquotesection", label: "Blockquote (sec)" },
  { value: "blogsection", label: "Blog (sec)" },
  { value: "bottomnavigationsection", label: "Bottom Navigation (sec)" },
  { value: "breadcrumbssection", label: "Breadcrumbs (sec)" },
  { value: "buttongroupsection", label: "Button Group (sec)" },
  // CCCC
  { value: "cardssection", label: "Cards (sec)" },
  { value: "cartsection", label: "Cart (sec)" },
  { value: "checkoutsection", label: "Checkout (sec)" },
  { value: "commentssection", label: "Comments (sec)" },
  { value: "contactssection", label: "Contacts (sec)" },
  { value: "cookiesection", label: "Cookie (sec)" },
  { value: "ctasection", label: "CTA (sec)" },
  // DDDD
  { value: "devicemockupsection", label: "Device Mockup (sec)" },
  { value: "dividersection", label: "Divider (sec)" },
  { value: "draweroffcanvassection", label: "Drawer (offcanvas) (sec)" },
  { value: "dropdownfiltersection", label: "Dropdown Filter (sec)" },
  { value: "dropdownsection", label: "Dropdown (sec)" },
  // EEEE
  { value: "errorBarsection", label: "ErrorBar (sec)" },
  // FFFF
  { value: "fAQsection", label: "FAQ (sec)" },
  { value: "featuressection", label: "Features (sec)" },
  { value: "floatinglabelsection", label: "Floating Label (sec)" },
  // GGGG
  { value: "gallerysection", label: "Gallery (sec)" },
  // HHHH
  {
    value: "horizontallinesection",
    label: "horizontal Line (HR) (sec)",
  },
  // IIII
  { value: "imagesection", label: "Image (sec)" },
  { value: "indicatorssection", label: "Indicators (sec)" },
  // JJJJ
  { value: "jumbotronsection", label: "Jumbotron (sec)" },
  // KKKK
  { value: "kbdkeyboardsection", label: "KBD (Keyboard) (sec)" },
  // LLLL
  { value: "linksection", label: "Link (sec)" },
  { value: "listgroupsection", label: "List Group (sec)" },
  { value: "listsection", label: "List (sec)" },
  { value: "loginformsection", label: "Login Form (sec)" },
  { value: "logoutformsection", label: "Logout Form (sec)" },
  // MMMM
  { value: "megamenusection", label: "Mega Menu (sec)" },
  { value: "menusection", label: "Menu (sec)" },
  { value: "modalsection", label: "Modal (sec)" },
  // NNNN
  { value: "newslettersection", label: "Newsletter (sec)" },
  // OOOO
  // PPPP
  { value: "paginationsection", label: "Pagination (sec)" },
  { value: "paragraphsection", label: "Paragraph (sec)" },
  { value: "partnerssection", label: "Partners (sec)" },
  { value: "popoversection", label: "Popover (sec)" },
  { value: "popupsection", label: "Popup (sec)" },
  { value: "pricingsection", label: "Pricing (sec)" },
  { value: "progressbarsection", label: "Progress bar (sec)" },
  // QQQQ
  // RRRR
  { value: "ratingsection", label: "Rating (sec)" },
  // SSSS
  { value: "searchinputsection", label: "Search Input (sec)" },
  { value: "sidebarsection", label: "Sidebar (sec)" },
  { value: "sidenavigationsection", label: "Side Navigation (sec)" },
  { value: "signupformsection", label: "Sign Up Form (sec)" },
  { value: "skeletonsection", label: "Skeleton (sec)" },
  { value: "speeddailsection", label: "Speed Dail (sec)" },
  { value: "stacksection", label: "Stack (sec)" },
  { value: "statisticssection", label: "Statistics (sec)" },
  { value: "stepperssection", label: "Steppers (sec)" },
  { value: "stepssection", label: "Steps (sec)" },
  { value: "stickybannersection", label: "Sticky Banner (sec)" },
  { value: "swapsection", label: "Swap (sec)" },
  // TTTT
  { value: "tableheadersection", label: "Table Header (sec)" },
  { value: "tablesection", label: "Table (sec)" },
  { value: "tabssection", label: "Tabs (sec)" },
  { value: "teamsection", label: "Team (sec)" },
  { value: "testimonialsection", label: "Testimonial (sec)" },
  { value: "textsection", label: "Text (sec)" },
  { value: "timelinesection", label: "Timeline (sec)" },
  { value: "toastsection", label: "Toast (sec)" },
  // VVVV
  { value: "videosection", label: "Video (sec)" },

  // Frontend Development
  { value: "Accessibility", label: "Accessibility" },
  { value: "Architecture", label: "Architecture" },
  { value: "Chrome DevTool", label: "Chrome DevTool" },
  { value: "Code", label: "Code" },
  { value: "Database", label: "Database" },
  { value: "Development", label: "Development" },
  { value: "Documentation", label: "Documentation" },
  { value: "JSON", label: "JSON" },
  { value: "Meta Tags", label: "Meta Tags" },
  { value: "Optimization", label: "Optimization" },
  { value: "Performance", label: "Performance" },
  { value: "Responsive", label: "Responsive" },
  { value: "Privacy", label: "Privacy" },
  { value: "PWA", label: "PWA" },
  { value: "QR Code", label: "QR Code" },
  { value: "SEO", label: "SEO" },
  { value: "Shortcut", label: "Shortcut" },
  { value: "SSR", label: "Server Sided Rendering (SSR)" },
  { value: "Structured Data", label: "Structured Data" },
  { value: "Test", label: "Test" },
  { value: "Web", label: "Web" },

  // Frontend Library
  { value: "Library", label: "Library" },
  { value: "WebRTC", label: "WebRTC" }, // Think of smth for this kind of libraries
  { value: "Angular.js", label: "Angular.js" },
  { value: "Next.js", label: "Next.js" },
  { value: "Nuxt.js", label: "Nuxt.js" },
  { value: "React.js", label: "React.js" },
  { value: "Vue.js", label: "Vue.js" },
  //   { value: "Redux", label: "Redux" }, // Also do the same with redux create tag called "State Management" put redux to it
  //   { value: "D3.js", label: "D3.js" }, // because d3.js is not big enough just create tag called graphs libray and put d3.js to it
  //   { value: "Zeplin", label: "Zeplin" },
  //   { value: "Bulma", label: "Bulma" },
  //   { value: "Semantic UI", label: "Semantic UI" }, // For all the ui component producing website 1 tag name
  //   { value: "Gatsby", label: "Gatsby" }, // "UI Components collection" then these components web link appears
  //   { value: "Material-UI", label: "Material-UI" },
  //   { value: "Chakra UI", label: "Chakra UI" },

  // Frontend UI/UX Design
  { value: "UIDesign", label: "UIDesign" },
  { value: "Icon", label: "Icon" },
  { value: "Video", label: "Video" },
  { value: "Picture", label: "Picture" },
  { value: "Color", label: "Color" },
  { value: "Gradient Color", label: "Gradient Color" },
  { value: "illustration", label: "illustration" },
  { value: "Inspiration", label: "Inspiration" },
  { value: "Typography", label: "Typography" },
  { value: "Font", label: "Font" },
  { value: "Music", label: "Music" },
  { value: "Animation", label: "Animation" },
  { value: "Pattern", label: "Pattern" },
  { value: "Blob", label: "Blob" },
  { value: "Wave", label: "Wave" },
  { value: "Emoji", label: "Emoji" },

  { value: "Interface", label: "Interface" },
  { value: "IOS", label: "IOS" },
  { value: "Android", label: "Android" },
  { value: "Google", label: "Google" },
  { value: "Desktop", label: "Desktop" },
  { value: "Screen", label: "Screen" },
  { value: "Awesome", label: "Awesome" },
  { value: "3D Image", label: "3D Image" },
  { value: "Social Media", label: "Social Media" },
  { value: "GIF", label: "GIF" },
  { value: "Template", label: "Template" },
  { value: "Wireframe", label: "Wireframe" },
  { value: "Logo", label: "Logo" },
  { value: "Prototype", label: "Prototype" },

  // Frontend Tools
  { value: "DesignTools", label: "DesignTools" },
  { value: "Adobe Illustrator", label: "Adobe Illustrator" }, // prototyping
  { value: "Adobe Photoshop", label: "Adobe Photoshop" },
  { value: "Adobe XD", label: "Adobe XD" },
  { value: "Sketch", label: "Sketch" },
  { value: "Figma", label: "Figma" },
  { value: "CSS", label: "CSS" }, // ui design code
  { value: "Bootstrap", label: "Bootstrap" },
  { value: "Sass", label: "Sass" },
  { value: "PostCSS", label: "PostCSS" },
  { value: "TailwindCSS", label: "TailwindCSS" },
  { value: "Less", label: "Less" },
  { value: "Styled Components", label: "Styled Components" },
  { value: "Generators", label: "Generators" },
  { value: "HTML", label: "HTML" },
  { value: "AI", label: "AI" },
  { value: "Extension", label: "Extension" },
  { value: "API", label: "API" },
  { value: "Browser", label: "Browser" },
  { value: "NoCode", label: "NoCode" },
  { value: "VS Code Tool", label: "VS Code Tool" },
  { value: "InVision Studio", label: "InVision Studio" },

  // Frontend Mixed
  { value: "Marketing", label: "Marketing" },
  { value: "Business", label: "Business" },
  { value: "Brand", label: "Brand" },
  { value: "Collection", label: "Collection" },
  { value: "Ant Design", label: "Ant Design" },
  { value: "Neumorphism", label: "Neumorphism" },
  { value: "Claymorphism", label: "Claymorphism" },
  { value: "Glassmorphism", label: "Glassmorphism" },
  { value: "GitHub", label: "GitHub" },

  //   Designer
  { value: "Designer", label: "Designer", isDisabled: true },
  { value: "User Reasercher", label: "User Reasercher" },
  { value: "Visual Designer", label: "Visual Designer" },
  { value: "Creative Director", label: "Creative Director" },
  { value: "Graphic Designer", label: "Graphic Designer" },
  { value: "Design Manager", label: "Design Manager" },
];

// { value: "SVG", label: "SVG" },
// { value: "PNG", label: "PNG" },
// { value: "JPEG", label: "JPEG" },
// { value: "GIF", label: "GIF" },
// { value: "JPG", label: "JPG" },

// { value: "TensorFlow", label: "TensorFlow" },
// { value: "PyTorch", label: "PyTorch" },
// { value: "scikit-learn", label: "scikit-learn" },
// { value: "Keras", label: "Keras" },
// { value: "MXNet", label: "MXNet" },
// { value: "Theano", label: "Theano" },
// { value: "Caffe", label: "Caffe" },
// //   Team Management
// { value: "JIRA", label: "JIRA" },
// { value: "Confluence", label: "Confluence" },
// { value: "Slack", label: "Slack" },
// { value: "Trello", label: "Trello" },
// { value: "Asana", label: "Asana" },
// { value: "Discord", label: "Discord" },
// { value: "React Native", label: "React Native" },
// { value: "Ionic", label: "Ionic" },
// { value: "Xamarin", label: "Xamarin" },
// { value: "Tableau", label: "Tableau" },
// { value: "Power BI", label: "Power BI" },
// { value: "R", label: "R" },
// { value: "Julia", label: "Julia" },
// { value: "Buildah", label: "Buildah" },
// { value: "NumPy", label: "NumPy" },
// { value: "Pandas", label: "Pandas" },
// { value: "Matplotlib", label: "Matplotlib" },
// { value: "Seaborn", label: "Seaborn" },

// export const FrontendOptions = [
//   { value: "Frontend", label: "Frontend", isDisabled: true },
//   // Frontend Layouts
//   { value: "contentlayout", label: "Content", color: "#FFD400" },
//   { value: "footerlayout", label: "Footer", color: "#FFD819" },
//   { value: "formslayout", label: "Forms", color: "#FFDD32" },
//   { value: "headerlayout", label: "Header", color: "#EDC4B3" },
//   { value: "herolayout", label: "Hero", color: "#E6B8A2" },
//   { value: "navbarlayout", label: "Navbar", color: "#DEAB90" },

//   // Frontend Components
//   { value: "Components", label: "Components", color: "#D69F7E" },
//   { value: "buttoncomp", label: "Button (comp)", color: "#CD9777" },
//   { value: "carouselcomp", label: "Carousel (comp)", color: "#C38E70" },
//   { value: "checkboxcomp", label: "Checkbox (comp)", color: "#B07D62" },
//   { value: "countdowncomp", label: "Countdown (comp)", color: "#9D6B53" },
//   { value: "datepickercomp", label: "Datepicker (comp)", color: "#8A5A44" },
//   { value: "fileinputcomp", label: "File Input (comp)", color: "#774936" },
//   { value: "inputfieldcomp", label: "Input Field (comp)", color: "#FF0A54" },
//   { value: "loadercomp", label: "Loader (comp)", color: "#FF477E" },
//   { value: "radiocomp", label: "Radio (comp)", color: "#FF5C8A" },
//   { value: "rangeslidercomp", label: "Range Slider (comp)", color: "#FF7096" },
//   { value: "selectcomp", label: "Select (comp)", color: "#FF85A1" },
//   { value: "spinnercomp", label: "Spinner (comp)", color: "#FF99AC" },
//   { value: "textareacomp", label: "Textarea (comp)", color: "#FBB1BD" },
//   { value: "togglecomp", label: "Toggle (comp)", color: "#F9BEC7" },
//   { value: "tooltipscomp", label: "Tooltips (comp)", color: "#F7CAD0" },

//   // Frontend Sections
//   { value: "Sections", label: "Sections", color: "#FAE0E4" },
//   // AAAA
//   { value: "aboutsection", label: "About (sec)", color: "#72BBCE" },
//   { value: "accordionsection", label: "Accordion (sec)", color: "#8DC8D8" },
//   { value: "alertsection", label: "Alert (sec)", color: "#A7D5E1" },
//   {
//     value: "applicationshellsection",
//     label: "Application Shell (sec)",
//     color: "#C2E2EA",
//   },
//   { value: "avatarsection", label: "Avatar (sec)", color: "#DCEEF3" },
//   // BBBB
//   { value: "badgessection", label: "Badges (sec)", color: "#ffe5ec" },
//   { value: "bannersection", label: "Banner (sec)", color: "#ffc2d1" },
//   { value: "blockquotesection", label: "Blockquote (sec)", color: "#ffb3c6" },
//   { value: "blogsection", label: "Blog (sec)", color: "#ff8fab" },
//   {
//     value: "bottomnavigationsection",
//     label: "Bottom Navigation (sec)",
//     color: "#fb6f92",
//   },
//   { value: "breadcrumbssection", label: "Breadcrumbs (sec)", color: "#fbf8cc" },
//   {
//     value: "buttongroupsection",
//     label: "Button Group (sec)",
//     color: "#ffcfd2",
//   },
//   // CCCC
//   { value: "cardssection", label: "Cards (sec)", color: "#f1c0e8" },
//   { value: "cartsection", label: "Cart (sec)", color: "#b9fbc0" },
//   { value: "checkoutsection", label: "Checkout (sec)", color: "#bed8fb" },
//   { value: "commentssection", label: "Comments (sec)", color: "#aecefa" },
//   { value: "contactssection", label: "Contacts (sec)", color: "#95bff9" },
//   { value: "cookiesection", label: "Cookie (sec)", color: "#8ab8f8" },
//   { value: "ctasection", label: "CTA (sec)", color: "#80b1f6" },
//   // DDDD
//   {
//     value: "devicemockupsection",
//     label: "Device Mockup (sec)",
//     color: "#CBF3F0",
//   },
//   { value: "dividersection", label: "Divider (sec)", color: "#7DDCD3" },
//   {
//     value: "draweroffcanvassection",
//     label: "Drawer (offcanvas) (sec)",
//     color: "#56D0C5",
//   },
//   {
//     value: "dropdownfiltersection",
//     label: "Dropdown Filter (sec)",
//     color: "#42CABE",
//   },
//   { value: "dropdownsection", label: "Dropdown (sec)", color: "#EC698F" },
//   // EEEE
//   { value: "errorBarsection", label: "ErrorBar (sec)", color: "#EE839F" },
//   // FFFF
//   { value: "fAQsection", label: "FAQ (sec)", color: "#F09CAF" },
//   { value: "featuressection", label: "Features (sec)", color: "#F1ADB9" },
//   {
//     value: "floatinglabelsection",
//     label: "Floating Label (sec)",
//     color: "#F3CFCE",
//   },
//   // GGGG
//   { value: "gallerysection", label: "Gallery (sec)", color: "#B8F2E6" },
//   // HHHH
//   {
//     value: "horizontallinesection",
//     label: "horizontal Line (HR) (sec)",
//     color: "#B6ECE5",
//   },
//   // IIII
//   { value: "imagesection", label: "Image (sec)", color: "#B3E6E3" },
//   { value: "indicatorssection", label: "Indicators (sec)", color: "#B3E6E3" },
//   // JJJJ
//   { value: "jumbotronsection", label: "Jumbotron (sec)", color: "#AED9E0" },
//   // KKKK
//   {
//     value: "kbdkeyboardsection",
//     label: "KBD (Keyboard) (sec)",
//     color: "#CCEEDE",
//   },
//   // LLLL
//   { value: "linksection", label: "Link (sec)", color: "#B3E8DC" },
//   { value: "listgroupsection", label: "List Group (sec)", color: "#99E1D9" },
//   { value: "listsection", label: "List (sec)", color: "#5ABEC2" },
//   { value: "loginformsection", label: "Login Form (sec)", color: "#3BACB6" },
//   { value: "logoutformsection", label: "Logout Form (sec)", color: "#DDFFF7" },
//   // MMMM
//   { value: "megamenusection", label: "Mega Menu (sec)", color: "#D1FAF2" },
//   { value: "menusection", label: "Menu (sec)", color: "#C4F5ED" },
//   { value: "modalsection", label: "Modal (sec)", color: "#B8F0E8" },
//   // NNNN
//   { value: "newslettersection", label: "Newsletter (sec)", color: "#ACEBE2" },
//   // OOOO
//   // PPPP
//   { value: "paginationsection", label: "Pagination (sec)", color: "#9FE6DD" },
//   { value: "paragraphsection", label: "Paragraph (sec)", color: "#93E1D8" },
//   { value: "partnerssection", label: "Partners (sec)", color: "#C4FFF9" },
//   { value: "popoversection", label: "Popover (sec)", color: "#B0F5F4" },
//   { value: "popupsection", label: "Popup (sec)", color: "#9CEAEF" },
//   { value: "pricingsection", label: "Pricing (sec)", color: "#82E1E3" },
//   {
//     value: "progressbarsection",
//     label: "Progress bar (sec)",
//     color: "#6BDAD9",
//   },
//   // QQQQ
//   // RRRR
//   { value: "ratingsection", label: "Rating (sec)", color: "#53D2CF" },
//   // SSSS
//   {
//     value: "searchinputsection",
//     label: "Search Input (sec)",
//     color: "#FFD400",
//   },
//   { value: "sidebarsection", label: "Sidebar (sec)", color: "#FFD819" },
//   {
//     value: "sidenavigationsection",
//     label: "Side Navigation (sec)",
//     color: "#FFDD32",
//   },
//   { value: "signupformsection", label: "Sign Up Form (sec)", color: "#FFE14C" },
//   { value: "skeletonsection", label: "Skeleton (sec)", color: "#FFE566" },
//   { value: "speeddailsection", label: "Speed Dail (sec)", color: "#FFE97F" },
//   { value: "stacksection", label: "Stack (sec)", color: "#FFEE99" },
//   { value: "statisticssection", label: "Statistics (sec)", color: "#FFF2B2" },
//   { value: "stepperssection", label: "Steppers (sec)", color: "#FFF6CC" },
//   { value: "stepssection", label: "Steps (sec)", color: "#FFFAE5" },
//   {
//     value: "stickybannersection",
//     label: "Sticky Banner (sec)",
//     color: "#93E1D8",
//   },
//   { value: "swapsection", label: "Swap (sec)", color: "#E1ECF7" },
//   // TTTT
//   {
//     value: "tableheadersection",
//     label: "Table Header (sec)",
//     color: "#AECBEB",
//   },
//   { value: "tablesection", label: "Table (sec)", color: "#A4C5E9" },
//   { value: "tabssection", label: "Tabs (sec)", color: "#99BEE6" },
//   { value: "teamsection", label: "Team (sec)", color: "#8EB7E4" },
//   { value: "testimonialsection", label: "Testimonial (sec)", color: "#83B0E1" },
//   { value: "textsection", label: "Text (sec)", color: "#7FAEE1" },
//   { value: "timelinesection", label: "Timeline (sec)", color: "#7AABE0" },
//   { value: "toastsection", label: "Toast (sec)", color: "#FFD78A" },
//   // VVVV
//   { value: "videosection", label: "Video (sec)", color: "#FDC77B" },

//   // Frontend Development
//   { value: "Accessibility", label: "Accessibility", color: "#FAA75C" },
//   { value: "Architecture", label: "Architecture", color: "#F8964C" },
//   { value: "Chrome DevTool", label: "Chrome DevTool", color: "#F78E45" },
//   { value: "Code", label: "Code", color: "#F7883F" },
//   { value: "Database", label: "Database", color: "#DAF5FE" },
//   { value: "Development", label: "Development", color: "#CAEFFB" },
//   { value: "Documentation", label: "Documentation", color: "#BAE8F8" },
//   { value: "JSON", label: "JSON", color: "#ADE2F4" },
//   { value: "Meta Tags", label: "Meta Tags", color: "#A0DCF0" },
//   { value: "Optimization", label: "Optimization", color: "#FFF0AD" },
//   { value: "Performance", label: "Performance", color: "#FFE985" },
//   { value: "Responsive", label: "Responsive", color: "#FFDD47" },
//   { value: "Privacy", label: "Privacy", color: "#FFD61F" },
//   { value: "PWA", label: "PWA", color: "#FFD100" },
//   { value: "QR Code", label: "QR Code", color: "#FFDAE4" },
//   { value: "SEO", label: "SEO", color: "#FDCCD9" },
//   { value: "Shortcut", label: "Shortcut", color: "#FCC5D4" },
//   { value: "SSR", label: "Server Sided Rendering (SSR)", color: "#F8BACB" },
//   { value: "Structured Data", label: "Structured Data", color: "#F1AAC2" },
//   { value: "Test", label: "Test", color: "#F2D8E3" },
//   { value: "Web", label: "Web", color: "#ECBED0" },

//   // Frontend Library
//   { value: "Library", label: "Library", color: "#E7A7C0" },
//   { value: "WebRTC", label: "WebRTC", color: "#E78FB2" }, // Think of smth for this kind of libraries
//   { value: "Angular.js", label: "Angular.js", color: "#E57AA5" },
//   { value: "Next.js", label: "Next.js", color: "#DDFFF7" },
//   { value: "Nuxt.js", label: "Nuxt.js", color: "#D1FAF2" },
//   { value: "React.js", label: "React.js", color: "#C4F5ED" },
//   { value: "Vue.js", label: "Vue.js", color: "#B8F0E8" },
//   // Frontend UI/UX Design
//   { value: "UIDesign", label: "UIDesign", color: "#ACEBE2" },
//   { value: "Icon", label: "Icon", color: "#9FE6DD" },
//   { value: "Video", label: "Video", color: "#93E1D8" },
//   { value: "Picture", label: "Picture", color: "#FFF5EC" },
//   { value: "Color", label: "Color", color: "#F6E7DB" },
//   { value: "Gradient Color", label: "Gradient Color", color: "#EDD9CA" },
//   { value: "illustration", label: "illustration", color: "#E4CAB9" },
//   { value: "Inspiration", label: "Inspiration", color: "#DBBCA8" },
//   { value: "Typography", label: "Typography", color: "#D1AE97" },
//   { value: "Font", label: "Font", color: "#BF9175" },
//   { value: "Music", label: "Music", color: "#B68364" },
//   { value: "Animation", label: "Animation", color: "#FF99C8" },
//   { value: "Pattern", label: "Pattern", color: "#FCF6BD" },
//   { value: "Blob", label: "Blob", color: "#D0F4DE" },
//   { value: "Wave", label: "Wave", color: "#A9DEF9" },
//   { value: "Emoji", label: "Emoji", color: "#E4C1F9" },

//   { value: "Interface", label: "Interface", color: "#EDF2FB" },
//   { value: "IOS", label: "IOS", color: "#E2EAFC" },
//   { value: "Android", label: "Android", color: "#D7E3FC" },
//   { value: "Google", label: "Google", color: "#CCDBFD" },
//   { value: "Desktop", label: "Desktop", color: "#C1D3FE" },
//   { value: "Screen", label: "Screen", color: "#B6CCFE" },
//   { value: "Awesome", label: "Awesome", color: "#ABC4FF" },
//   { value: "3D Image", label: "3D Image", color: "#ef6351" },
//   { value: "Social Media", label: "Social Media", color: "#f38375" },
//   { value: "GIF", label: "GIF", color: "#f7a399" },
//   { value: "Template", label: "Template", color: "#fbc3bc" },
//   { value: "Wireframe", label: "Wireframe", color: "#ffe3e0" },
//   { value: "Logo", label: "Logo", color: "#d3f8e2" },
//   { value: "Prototype", label: "Prototype", color: "#e4c1f9" },

//   // Frontend Tools
//   { value: "DesignTools", label: "DesignTools", color: "#f694c1" },
//   { value: "Adobe Illustrator", label: "Adobe Illustrator", color: "#ede7b1" }, // prototyping
//   { value: "Adobe Photoshop", label: "Adobe Photoshop", color: "#a9def9" },
//   { value: "Adobe XD", label: "Adobe XD", color: "#A1EF7A" },
//   { value: "Sketch", label: "Sketch", color: "#B0EF8E" },
//   { value: "Figma", label: "Figma", color: "#BAF19C" },
//   { value: "CSS", label: "CSS", color: "#C5F3AB" }, // ui design code
//   { value: "Bootstrap", label: "Bootstrap", color: "#D0F4BA" },
//   { value: "Sass", label: "Sass", color: "#EAF8DA" },
//   { value: "PostCSS", label: "PostCSS", color: "#90F1EF" },
//   { value: "TailwindCSS", label: "TailwindCSS", color: "#FFD6E0" },
//   { value: "Less", label: "Less", color: "#FFEF9F" },
//   { value: "Styled Components", label: "Styled Components", color: "#C1FBA4" },
//   { value: "Generators", label: "Generators", color: "#7BF1A8" },
//   { value: "HTML", label: "HTML", color: "#BAF2BB" },
//   { value: "AI", label: "AI", color: "#BAF2D8" },
//   { value: "Extension", label: "Extension", color: "#BAD7F2" },
//   { value: "API", label: "API", color: "#F2BAC9" },
//   { value: "Browser", label: "Browser", color: "#F2E2BA" },
//   { value: "NoCode", label: "NoCode", color: "#70D6FF" },
//   { value: "VS Code Tool", label: "VS Code Tool", color: "#FF70A6" },
//   { value: "InVision Studio", label: "InVision Studio", color: "#FF9770" },

//   // Frontend Mixed
//   { value: "Marketing", label: "Marketing", color: "#FFD670" },
//   { value: "Business", label: "Business", color: "#E9FF70" },
//   { value: "Brand", label: "Brand", color: "#EE6055" },
//   { value: "Collection", label: "Collection", color: "#60D394" },
//   { value: "Ant Design", label: "Ant Design", color: "#AAF683" },
//   { value: "Neumorphism", label: "Neumorphism", color: "#FFD97D" },
//   { value: "Claymorphism", label: "Claymorphism", color: "#FF9B85" },
//   { value: "Glassmorphism", label: "Glassmorphism", color: "#ff686b" },
//   { value: "GitHub", label: "GitHub", color: "#ffa69e" },

//   //   Designer
//   { value: "Designer", label: "Designer", isDisabled: true },
//   { value: "User Reasercher", label: "User Reasercher", color: "#a5ffd6" },
//   { value: "Visual Designer", label: "Visual Designer", color: "#84dcc6" },
//   { value: "Creative Director", label: "Creative Director", color: "#ffffff" },
//   { value: "Graphic Designer", label: "Graphic Designer", color: "#ffa69e" },
//   { value: "Design Manager", label: "Design Manager", color: "#ffa69e" },
// ];
